### PR TITLE
NSIS auto-update doesn't use system HTTP proxy (#959)

### PR DESCRIPTION
**Pull request by maczikasz**
feat: Use Electron.Net to send http requests for auto updater

There was a refactoring around httpRequests and util/restApiRequests, they both forward the calls to an instance of the HttpExecutor interface, which can be Node or Electron. Node is used by default and electron is only used in case it's an electron app running the auto updater

### CODE REVIEW

**Comment by maczikasz** [comment]
I haven't tested it yet on the corporate proxy, but electron net works so I assume it will work also, but I can verify on monday

**Comment by develar** [comment]
I have merged PR with some changes:

* no need to pass httpExecutor — we can just use executorHolder
* no need to add electron to dependencies.
* no need to add electron typings to nsis-auto-updater — parent typings is enough. Probably later nsis-auto-updater will be standalone package, but for now it anyway uses sources of electron-builder.

I didn't publish nsis-auto-updater because i didn't check it manually and our current test suite doesn't test auto update anymore — we must run nsisUpdaterTest against electron, but not node (probably using https://github.com/segmentio/nightmare). It will be cool if you will implement it, because no sense to test auto updater using node if it differs from the real app.

**Comment by develar** [comment]
@maczikasz Thank you, without your PR this important task was postponed for a unknown time.

**Comment by maczikasz** [comment]
Thank you for merging the PR, I will do a manual test today on our proxy ( I did manual test w/o proxy just proving regression). Thanks for cleaning it up a bit, as you see I am not a JS/TS dev so I had some fears that I had written in a very stupid/weird manner :)

I completely agree with your statement about the tests, I will try to implement them with the lib you suggested, let's see if I can make it work.

**Comment by maczikasz** [comment]
Fyi it works behind our corporate proxy manually, but I will still try to do the tests (possibly with Spectron rather than nightmare)

**Comment by maczikasz** [comment]
Hi @develar do I see right you released a new version of the auto-updater after all? I see a release in npm, but I thought it will not get released.

Anyway I will finish the tests in beginning on Jan, I have a FW that would work but I have an issue with Spectron (https://github.com/electron/spectron/issues/153) which stops me from being able to actually do it :(

Will update you if there is any progress there

**Comment by develar** [comment]
I trust you and as you reported that it works I decided to publish because feature that you implemented is awesome.

**Pull request closed without merging**
