### PR TITLE
fix(dmg-builder): exec python fail on Macos12.3

### PR DESCRIPTION
**Pull request by bytemain**
close: #6767

### CODE REVIEW

**Comment by mmaietta** [comment]
This change is causing all mac dmg tests to fail as it's trying to use python @ `/usr/local/bin/python`
```
FAIL  src/mac/dmgTest.ts (585.119 s)
  ✕ dmg (13943 ms)

  ● dmg

    Exit code: ENOENT. spawn /usr/local/bin/python
     ENOENT

      131 |           }
      132 |
    > 133 |           reject(new Error(message))
          |                  ^
      134 |         }
      135 |       }
      136 |     )

      at ../packages/builder-util/src/util.ts:133:18
```

Unfortunately, github actions doesn't have a MacOS 12 build machine yet otherwise I'd be running our tests on that.

**Comment by bytemain** [comment]
it seem that `which python` got a result: `/usr/local/bin/python`.

but why it does not exists

**Comment by bytemain** [comment]
it seem that I have fixed it.

the return value of `exec` func has a `'\n'` suffix.

**Comment by mmaietta** [comment]
Thank you for your contribution!

Seems the Docs automation is frozen, but the CI tests all passed. Merging now

**Pull request merged**
