### PR TITLE
Finish support for notarization

### PR DESCRIPTION
**Pull request by Kilian**
As per #3870, this PR adds two new options:

*`gatekeeperAssess` in macOptions (defaults to true) _Allows people to disable the gatekeeper assessment while osx-sign fails on that (see https://github.com/electron-userland/electron-osx-sign/issues/196)_
*`sign` in dmgOptions (defaults to false) _signing the dmg does not appear to be needed and actually prevents people from opening the dmg in 10.14.5, see #3870._

Together with the afterSign hook where people can call `electron-notarize`, these options let `electron-builder` user successfully create a notarized application in a DMG that does not show warning messages.

### CODE REVIEW

**Comment by Kilian** [comment]
@develar Can you take a look at this? I don't really see why the appVeyor or travis builds would fail on this (failures seem unrelated too?)

**Comment by lane-c-wagner** [comment]
Looks like some dependency errors:
```
 TypeError: cb.apply is not a function
      at node_modules/graceful-fs/polyfills.js:285:20
```

https://ci.appveyor.com/project/stefanjudis/electron-builder/builds/24832175#L244

I would guess some updates are in order?

**Comment by lane-c-wagner** [comment]
I also just tried testing sections of this PR against travis and appveyor.. I have no idea why these errors are being thrown. Although they look like they are linked to fs-extra-p @develar

**Comment by lane-c-wagner** [comment]
Idk if this will be taken care of, but @Kilian I copied the "out" folder from app-builder-lib and dmg-builder in order to get this working for myself because its taking so long to get this merged.

I noticed that there is a bug in app-builder-lib where it is saying gatekeeperAssess is not a valid configuration option (on your branch). For myself I hard coded it but this may be a problem here.

**Comment by Kilian** [comment]
@lane-c-wagner did you put gatekeeperAssess in the `mac` configuration or in the `dmg` configuration? It should go in the former.

**Comment by guanxun14** [comment]
Thank you @develar for the commit. As I [understand the situation](https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db), this commit effectively solves the notarization situation as far as electron-build is concerned. May I just check if you will be tagging this as a release, or might there be more needed before it's ready? Thanks again! :)

**Comment by develar** [comment]
20.43.0 released.

**Comment by raymondjacobson** [comment]
After bumping the version and trying this out, I'm seeing
`Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)`

when trying to open the App. The actual disk image mounts fine.

`codesign --verify -vvvv /Volumes/App/App.app`

gives me 
```
--prepared:/Volumes/App/App.app/Contents/Frameworks/App Helper.app
--validated:/Volumes/App/App.app/Contents/Frameworks/App Helper.app
--prepared:/Volumes/App/App.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--validated:/Volumes/App/App.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--prepared:/Volumes/App/App.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--validated:/Volumes/App/App.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--prepared:/Volumes/App/App.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
--validated:/Volumes/App/App.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
--prepared:/Volumes/App/App.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--validated:/Volumes/App/App.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
/Volumes/App/App.app: valid on disk
/Volumes/App/App.app: satisfies its Designated Requirement
```

And 
`spctl -a -v /Volumes/App/App.app`

gives
```
/Volumes/App/App.app: accepted
source=Notarized Developer ID
```

Has anyone seen this?

**Comment by lane-c-wagner** [comment]
Did you get the entitlements right? I saw this before I fixed my
entitlements

**Comment by raymondjacobson** [comment]
Looks that that was probably the issue :) Particularly this one, I think? 
`<key>com.apple.security.cs.allow-unsigned-executable-memory</key>`

thx Lane!

**Comment by itsthisjustin** [comment]
@raymondjacobson We only have 1 single entitlement, com.apple.security.files.user-selected.read-write and getting this on our app. Is there anything else that would cause it?

**Comment by raymondjacobson** [comment]
@itsthisjustin Sorry, just saw this message. FWIW, this is what I've done

You may not need all of these.

`
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-only</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
`

**Comment by itsthisjustin** [comment]
@raymondjacobson Thanks. I finally got it working. Notarization has unfortunately caused a new issue that I'm wondering if you or @Kilian have come across. 

Node-notifier has this weird issue where it comes default with the terminal icon and you have to manually copy your app's icon over top it in the node_modules folder. This has been working fine for us and the way we do it is by copying over a new info.plist and the icon so it shows as fresh and then unasar-ing it in the build command. 

So, now with notarization, Apple gives us back this error:

> The binary is not signed with a valid Developer ID certificate
with a link to the node notifier package. 

Any tips on how to have my cake and eat it too?

**Pull request closed without merging**
