### PR TITLE
refactor: remove stale handler for `extend-info`

### PR DESCRIPTION
**Pull request by t3chguy**
The `extend-info` read was removed in a23e68066b3912110024d219507f5691fd14e450 so this if statement never runs

### CODE REVIEW

**Comment by mmaietta** [comment]
Great catch. How did you determine that it was stale?
`decode-plist` is an undocumented function in https://github.com/develar/app-builder but AFAICT, it shouldn't be returning any entry at that array index either
https://github.com/develar/app-builder/blob/d971224691f6f48555e2a9bb327f99627893372c/pkg/plist/plist.go#L68-L70

**Comment by t3chguy** [comment]
> Great catch. How did you determine that it was stale?

I was looking at ways to work around https://github.com/electron-userland/electron-builder/issues/8660 by injecting my own data into the asar without it being nuked by the asar integrity calculation and thought `extend-info` was my golden ticket. Sadly not.

Prior to the linked commit `extend-info` was a value on `buildMetadata` (`(buildMetadata as any)["extend-info"]`) but there is no longer such a key anywhere else in the codebase and indeed the undocumented function returns the same amount as you put in.

**Comment by mmaietta** [comment]
Are you referring to this `extendInfo` functionality?
```
mac: {
  // test appId per platform
  appId: "foo",
  extendInfo: {
    LSUIElement: true,
    CFBundleDocumentTypes: [
      {
        CFBundleTypeName: "Folders",
        CFBundleTypeRole: "Editor",
        LSItemContentTypes: ["public.folder"],
      },
    ],
  },
}
```

**Comment by t3chguy** [comment]
Yes, sadly the ASAR integrity thing just overwrites the field rather than merging into it

**Pull request merged**
