### PR TITLE
Remove redundant signing op for mas and mas-dev targets

### PR DESCRIPTION
**Pull request by oNaiPs**
I noticed that running the packager on a basic vanilla repo was yielding two signing operations for mas/mas-dev targets:
```
mkdir test && cd test
yarn init
yarn add --dev electron electron-builder
echo "console.log('hello world')" > index.js
yarn electron-builder -m mas
  • electron-builder  version=21.2.0 os=18.7.0
  • description is missed in the package.json  appPackageFile=/Users/onaips/test/package.json
  • author is missed in the package.json  appPackageFile=/Users/onaips/test/package.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=mas arch=x64 electron=6.0.12 appOutDir=dist/mas
  • default Electron icon is used  reason=application icon is not set
  • signing         file=dist/mas/test.app identityName=Developer ID Application: -redacted- identityHash=-redacted- provisioningProfile=none
  • signing         file=dist/mas/test.app identityName=3rd Party Mac Developer Application:-redacted- identityHash=-redacted- provisioningProfile=none
```

I think this is an artifact from [this](https://github.com/electron-userland/electron-builder/commit/f4398a7225c88880f9dee755b6c14699adf91c27) PR after this [other one](https://github.com/electron-userland/electron-builder/pull/3912) was implemented

This PR removes the unneeded intermediate package signing.

### CODE REVIEW

**Comment by oNaiPs** [comment]
It looks like these signing operation are indeed needed, since the `signApp` is called with any MAS options.
Perhaps way to go would be to instead skip the regular signing called on `doPack` from `platformPackager.ts`?

**Comment by oNaiPs** [comment]
OK should be fixed now.

**Comment by tflack** [comment]
> OK should be fixed now.

CI is failing because of an extra semi colon...

**Comment by oNaiPs** [comment]
@tflack should be fixed now.

**Comment by develar** [comment]
Thanks!

**Comment by patrickmichalina** [comment]
FYI: This new code has broken "DMG" signing.

**Comment by quanglam2807** [comment]
I agree, @patrickmichalina. This PR has regression. It disables signing altogether if `mas` is in `targets`. So if `targets` include non-mas like `dmg`, `zip` together with `mas`, non-mas builds won't be signed.  Would you mind providing a fix, @oNaiPs?

**Comment by gaodeng** [comment]
please revert this commit https://github.com/electron-userland/electron-builder/commit/56922819f0be39fffb31bbb50437ad4fcdde7365  @develar

**Comment by develar** [comment]
Reverted.

**Pull request merged**
