### PR TITLE
fix(windows): detect node path correctly on windows with cross-spawn (#6069)

### LINKED ISSUE #6069: The path of node js is not correctly recognized on Windows
* **Electron-Builder Version**: 22.11.7

* **Node Version**: 14.17.3

* **Electron Version**: 13.1.6
* **Electron Type (current, beta, nightly)**: current

* **Target**: N/A

While running installing-app-deps or any other commands, following error occurs:
```
  • electron-builder  version=22.11.7
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=win32 arch=x64 appDir=D:\dev\cryptoElectron\src
  • spawning        command=C:\Users\Losse\AppData\Local\Temp\xfs-8e15e263\node yarn install --production cwd=D:\dev\cryptoElectron\src
  • exited          command=node code=-4058 pid=undefined
  ⨯ spawn C:\Users\Losse\AppData\Local\Temp\xfs-8e15e263\node ENOENT  failedTask=installAppDeps stackTrace=Error: spawn C:\Users\Losse\AppData\Local\Temp\xfs-8e15e263\node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

This may relate to the `spawn` method, the closest code I found is:
https://github.com/electron-userland/electron-builder/blob/5b4305ec336cf6f5866a26cde7fe99f18d7ac566/packages/app-builder-lib/src/util/yarn.ts#L108

### PR DESCRIPTION
**Pull request by Losses**
This Pull request would fix #6069

### CODE REVIEW

**Comment by mmaietta** [comment]
Nice detective work!

Do we need to worry about a similar issue in `NsisUpdater` using `child_process`?
https://github.com/electron-userland/electron-builder/blob/695f89a7b18e100c15ac47f837ae10ee600710ac/packages/electron-updater/src/NsisUpdater.ts#L231-L234

**Comment by mmaietta** [comment]
Please take a look at the failing tests:
>Error: Cannot spawn /__w/electron-builder/electron-builder/node_modules/.pnpm/app-builder-bin@3.7.1/node_modules/app-builder-bin/linux/x64/app-builder: TypeError: cross_spawn_1.default is not a function

**Comment by Losses** [comment]
> Please take a look at the failing tests:
> 
> > Error: Cannot spawn /__w/electron-builder/electron-builder/node_modules/.pnpm/app-builder-bin@3.7.1/node_modules/app-builder-bin/linux/x64/app-builder: TypeError: cross_spawn_1.default is not a function

I think these code doesn't need to be modified, I didn't find any error in this place when I packaged our application.

**Comment by Losses** [comment]
> Nice detective work!
> 
> Do we need to worry about a similar issue in `NsisUpdater` using `child_process`?
> https://github.com/electron-userland/electron-builder/blob/695f89a7b18e100c15ac47f837ae10ee600710ac/packages/electron-updater/src/NsisUpdater.ts#L231-L234

I think these code doesn't need to be modified, I didn't find any error in this place when I packaged our application.

**Pull request merged**
