### PR TITLE
Add feature to override the Mac PKG component plist

### PR DESCRIPTION
**Pull request by pronebird**
This PR adds ability to override the component plist provided to `pkgbuild`, discussed in #1838 

The example YML configuration:

```yml
pkg:
  isRelocatable: true
  isVersionChecked: true
  hasStrictIdentifier: true
  overwriteAction: "upgrade"
```

The new options that I've added correspond to the options in component plist file saved and consumed by `pkgbuild`, this is the `man` page excerpt:

> COMPONENT PROPERTY LIST
>      When you package a destination root, you can use a component property list to specify how bundles in
>      that root should be handled by the OS X Installer. This property list should be an array of dictionar-
>      ies, where each dictionary specifies a single bundle. The dictionary keys are as follows:
> 
>      Key                            Description
>      RootRelativeBundlePath         Path to bundle relative to the destination root (string)
>      BundleIsRelocatable            Install bundle over previous version if moved by user? (bool)
>      BundleIsVersionChecked         Don't install bundle if newer version on disk? (bool)
>      BundleHasStrictIdentifier      Require identical bundle identifiers at install path? (bool)
>      BundleOverwriteAction          How to treat existing on-disk version of bundle (string)
>      BundlePreInstallScriptPath     Relative path to bundle-specific preinstall script
>      BundlePostInstallScriptPath    Relative path to bundle-specific postinstall script
>      ChildBundles                   Bundles under this bundle (array of dictionaries)

I ran `yarn run docs` but It seems that docs haven't been updated in a while so I'll leave it up to somebody else to send a PR with the generated docs. I don't want to commit that many changes, some of which didn't look right :)

### CODE REVIEW

**Comment by pronebird** [comment]
The relevant test passed on Travis, however the unrelated job went into infinite execution.

**Comment by develar** [comment]
Thanks a lot, sorry for delay.

**Comment by pronebird** [comment]
@develar that's alright! Could you please make a release or pre-release? I really need this feature.

**Comment by p120ph37** [comment]
This addressed #1711

**Pull request closed without merging**
