### PR TITLE
feat: Add option for whether to check package.json semver compliance

### PR DESCRIPTION
**Pull request by dr-vortex**
This PR adds the `checkPackageVersion` config option. When set to `false`, the `version` field of `package.json` will not be checked for semver compliance. When set to `true` (the default), it will have the current behavior.

### CODE REVIEW

**Comment by mmaietta** [comment]
Is this implementing a specific issue? Looking to understand the context as to why we wouldn't want to verify semver compliance.

**Comment by dr-vortex** [comment]
This is related to #7173: For applications not published to a registry, the `version` field of `package.json` does not need to be semver.  When trying to build when this is the case, it fails regardless of whether `extraMetadata.version` is set.

**Comment by mmaietta** [comment]
@dr-vortex semver validation for Windows was already removed in Oct 2022.
https://github.com/electron-userland/electron-builder/pull/7174

**Comment by dr-vortex** [comment]
@mmaietta I saw this PR. Semver validation was not removed for the `version` field of package.json.

**Comment by mmaietta** [comment]
I'm always wary of adding a new option to the configuration but IIRC, this PR also broke numerous unit tests. I'll reopen this, but you'll need to take an alternative approach. What is your `version` format?

**Comment by dr-vortex** [comment]
@mmaietta I'm using a non-semver for `version`. Since I depend on the version in other parts of the application, I put it in package.json instead of using config specific to electron-builder.

The tests may need to be updated if they check against the old config interface.

**Comment by dr-vortex** [comment]
Also, I have not made any commits since I renamed the PR so checks will need to be run again.

**Comment by mmaietta** [comment]
Hi @dr-vortex, I've rerun all tests and they're still failing due to changes in this PR

**Comment by dr-vortex** [comment]
The semantic versioning enforcer (which checks for PR title prefixes) is failing despite the prefix existing.

**Comment by mmaietta** [comment]
Incorrect. Please see `Test / test-mac` and `Test / test-linux` test failures

**Comment by dr-vortex** [comment]
Note that this is still broken. 
Resolves #7789

**Comment by mmaietta** [comment]
Note, your PR is still broken
https://github.com/electron-userland/electron-builder/pull/7639#issuecomment-1640380943

**Comment by dr-vortex** [comment]
> Note that this is still broken. 
> Resolves #7789 

I was talking about the PR here

**Comment by mmaietta** [comment]
The back-and-forth on this PR disregarding your code failing to pass the unit test suite is rather a nuisance. Closing PR and unsubscribing from this. I'll look forward to more productive conversations elsewhere

**Comment by james-pre** [comment]
@mmaietta I've updated my GitHub username from @dr-vortex to @james-pre. Please update your comment(s), and I can delete this one. I'm writing this comment when I can't make the change myself.

**Pull request closed without merging**
