### PR TITLE
fix(app-builder-lib): allow not to specify sha1 for signing certificate

### LINKED ISSUE #4626: "Cannot find certificate" on Windows when EV signing
* **Version**: 22.3.2

* **Target**: Win x64

We're upgrading from version `20.28.4`. Our previous build pipeline worked great. Just updated to `22.3.2` and we get the `Cannot find certificate` error now.

In `package.json`:
```
 "win": {
      "publisherName": "Bark Technologies, Inc",
      "certificateSubjectName": "Bark Technologies, Inc"
    }
```

```
PS C:\Users\bh> Get-ChildItem -Recurse Cert: -CodeSigningCert | Select-Object -Property Subject,PSParentPath,Thumbprint | ConvertTo-Json -Compress
{"Subject":"CN=\"Bark Technologies, Inc\", O=\"Bark Technologies, Inc\", L=Atlanta, S=Georgia, C=US, SERIALNUMBER=5783034, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.2=Delaware, OID.1.3.6.1.4.1.311.60.2.1.3=US","PSParentPath":"Microsoft.PowerShell.Security\\Certificate::CurrentUser\\My","Thumbprint":"E458FBF56BA4C15003C647EAE58B1D2FF8AA38E2"}
```

Any ideas?

### PR DESCRIPTION
**Pull request by Jasyer**
Previous code didn't support the case when subject name was specified but sha1 wasn't.

Fixes #4626

### CODE REVIEW

**Comment by Jasyer** [comment]
Fixes #4626

**Comment by kzimny** [comment]
There are other similar issue #4631 and https://github.com/electron-userland/electron-builder/pull/4499

**Comment by develar** [comment]
Please resolve merge conflicts.

**Comment by Jasyer** [comment]
> Please resolve merge conflicts.

Done

**Pull request merged**
