### PR TITLE
docs(windows): document Windows max variable length limit

### PR DESCRIPTION
**Pull request by jviotti**
Fixes: https://github.com/electron-userland/electron-builder/issues/1902
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>

### CODE REVIEW

**Comment by jviotti** [comment]
I tried running `yarn api`, but I get:

```
$ yarn api
yarn api v0.27.5
$ yarn jsdoc && yarn jsdoc2md
Generating JSDoc to /Users/jviotti/Projects/playground/electron-builder/scripts/jsdoc/out/http
Generating JSDoc to /Users/jviotti/Projects/playground/electron-builder/scripts/jsdoc/out/updater
Generating JSDoc to /Users/jviotti/Projects/playground/electron-builder/scripts/jsdoc/out/util
exception evaluating initializer for property options
exception evaluating initializer for property options
exception evaluating initializer for property progress
exception evaluating initializer for property options
exception evaluating initializer for property options
exception evaluating initializer for property options
Generating JSDoc to /Users/jviotti/Projects/playground/electron-builder/scripts/jsdoc/out/builder
Generating JSDoc to /Users/jviotti/Projects/playground/electron-builder/scripts/jsdoc/out/publisher
/Users/jviotti/Projects/playground/electron-builder/scripts/jsdoc2md.js:10
async function main() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
error Command failed with exit code 1.
error Command failed with exit code 1.
```

Maybe I'm missing something?

**Comment by develar** [comment]
@jviotti Node 8 is required for development.

**Comment by develar** [comment]
> try re-exporting the certificate without including all the certificates in the certification path

Apple export works without intermediate certs. How do you export win cert, that intermediate certs are included? In the docs, we should mention, that intermediate certs are not required.

**Comment by jviotti** [comment]
I'll update the PR.

> Apple export works without intermediate certs.

Yep. In the case of Windows, I had a Comodo standard certificate, and the Comodo certificate itself was included as part of the certificate path.

> How do you export win cert, that intermediate certs are included?

I guess it depends on how you manage Windows certificate. The Windows Certificate Manager export wizard ticks an option to include the whole certificate path by default.

> In the docs, we should mention, that intermediate certs are not required.

I'll clarify that.

**Pull request merged**
