### PR TITLE
Fix appindicator icons with snap build

### LINKED ISSUE #1452: Indicator icons are broken in snaps of Electron applications.
Which version of electron-builder are you using?
  * **Version**: 16.8.2

What target are you building for?
* **Target**: Linux. snap

When building snaps for Linux the Indicator icons (if supported by the applications) have broken image icons. This can be resolved by coercing the `TMPDIR` path for Chromium Framework/Electron to ensure `libappindicator` has readable resources. For example:

```
apps:
  example:
    # Correct the TMPDIR path for Chromium Framework/Electron to
    # ensure libappindicator has readable resources.
    command: env TMPDIR=$XDG_RUNTIME_DIR ${SNAP}/bin/desktop-launch $SNAP/usr/bin/example
```

Coercing TMPDIR is a safe default for all snapped Electron applications.

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Closes #1452

Credit to: @flexiondotorg for the exact fix :smile:

### CODE REVIEW

**Comment by develar** [comment]
Are your sure that it is safe to change `TMPDIR` for the whole app? Why default `TMPDIR` is not readable?

**Comment by geekgonecrazy** [comment]
My understanding from the snap team is that it's safe for any graphical application like electron to always have this.  

I'll see if I can figure out the snapTest command.

**Comment by develar** [comment]
Why TMPDIR is not readable? Could you please explain?

**Comment by flexiondotorg** [comment]
XDG_RUNTIME_DIR is set by `snapd` and points to `/run/user/<UID>/snap.<snapname>/`

  * https://github.com/snapcore/snapd/blob/7d46f0d32c3db67543ccc14c580a643097727944/snap/snapenv/snapenv.go#L94

**Comment by develar** [comment]
So... it is more safe to change `TMPDIR`. Ok. Could you please update snapshot to fix CI? Or I can do it.

**Comment by geekgonecrazy** [comment]
@develar thanks for merging! :+1:

**Comment by develar** [comment]
Release will be tomorrow morning CET.

**Pull request merged**
