### PR TITLE
fix(msi): put appId in file shortcut to fix notifications in win8/win10

### LINKED ISSUE #2906: MSI for Win10 does not have working Notification
* **Version**: v20.13.3

* **Target**: msi, win10 (x64)
According to this thread https://github.com/electron/electron/issues/10864#issuecomment-372228945 Win10 has the same problem as Win8 where a shortcut file with a reference to the appId must be placed in the start menu. 

In the PR to follow, I've confirmed that adding `app.setAppUserModelId(appId)`, along with such a shortcut configured in the WXS file causes `new Notification(...).show()` to work in at least Win10.

References:
- https://github.com/electron/electron/issues/10864#issuecomment-372638523
- http://wixtoolset.org/documentation/manual/v3/xsd/wix/shortcutproperty.html
- https://msdn.microsoft.com/en-us/library/windows/desktop/hh802768 : 
> "A shortcut to your app, with a System.AppUserModel.ID, must be installed to the Start screen. Note, however, that it does not need to be pinned to the Start screen. For more information, see How to enable desktop toast notifications through an AppUserModelID."

### PR DESCRIPTION
**Pull request by saifelse**
Close #2906

### CODE REVIEW

**Comment by saifelse** [comment]
No problem, the speedy review is appreciated!

@develar: do you think there could be a release for this? I'd like to have this work for an app I'm trying to release soon, but electron-builder's build process adds a decent amount of complexity. Thanks!

**Comment by develar** [comment]
@saifelse 20.13.4 released for you.

**Comment by akashnimare** [comment]
@saifelse, @develar I'm using electron-builder `v20.40.2` and looks like the notification is not working for MSI target. Works well for NSIS. I'm manually setting the appID on app start. Code [here](https://github.com/zulip/zulip-desktop/search?q=appID&unscoped_q=appID). Can you guys help?

**Comment by akashnimare** [comment]
@saifelse, @develar I'm using electron-builder `v20.40.2` and looks like the notification is not working for MSI target. Works well for NSIS. I'm manually setting the appID on app start. Code [here](https://github.com/zulip/zulip-desktop/search?q=appID&unscoped_q=appID). Can you guys help?

**Pull request merged**
