### PR TITLE
fix: missing @types dependencies for output d.ts files

### PR DESCRIPTION
**Pull request by t3chguy**
Regressed by https://github.com/electron-userland/electron-builder/pull/7508
Similar to https://github.com/electron-userland/electron-builder/issues/4556
https://github.com/electron-userland/electron-builder/pull/4574 is the previous incarnation of this PR

Fixes failures like https://github.com/vector-im/element-desktop/actions/runs/4860501384/jobs/8664396114?pr=641

### CODE REVIEW

**Comment by mmaietta** [comment]
Thank you for tackling this. Will get it merged asap.

**Comment by mmaietta** [comment]
Hmmm can you run `pnpm install` again?

I'm seeing CI build errors
```
 ERR_PNPM_FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE  Cannot perform a frozen installation because the lockfile needs updates

```

**Comment by t3chguy** [comment]
```
 ~/W/electron-builder   t3chguy/@types  pnpm install                                                                                                                           Fri May  5 17:31:32 2023
Scope: all 14 workspace projects
 WARN  There are cyclic workspace dependencies: /Users/t3chguy/WebstormProjects/electron-builder/packages/app-builder-lib, /Users/t3chguy/WebstormProjects/electron-builder/packages/dmg-builder; /Users/t3chguy/WebstormProjects/electron-builder/packages/app-builder-lib, /Users/t3chguy/WebstormProjects/electron-builder/packages/dmg-builder, /Users/t3chguy/WebstormProjects/electron-builder/packages/app-builder-lib, /Users/t3chguy/WebstormProjects/electron-builder/packages/electron-builder-squirrel-windows
Lockfile is up to date, resolution step is skipped
Already up to date
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 251ms
Done in 1.5s
```

looks like it has nothing to do

**Comment by t3chguy** [comment]
Misclick, my bad. Tried again using pnpm 7 (had 8 installed previously)

**Pull request merged**
