### PR TITLE
fix: @electron/remote wrongly into Windows app.asar

### PR DESCRIPTION
**Pull request by beyondkmp**
Fix https://github.com/electron-userland/electron-builder/issues/8252

### CODE REVIEW

**Comment by beyondkmp** [comment]
@mmaietta I found a new bug if we alias node module name. Please help revivew: https://github.com/develar/app-builder/pull/119

**Comment by beyondkmp** [comment]
@mmaietta It seems like the CI has a cache, comparing with the previous snapshot. Often, the first run fails, and then it succeeds on a rerun without any changes. I haven't found the root cause yet.

**Comment by mmaietta** [comment]
@beyondkmp thank you! Reran the CI and it all passes, I'm not sure re: the caching issue but it is indeed leading to a flaky CI (which needs fixing for sure)

Does this PR depend on a release of the app-builder-bin changes as well?

**Comment by beyondkmp** [comment]
There's no interdependency. However, I think we can integrate the new app-builder-bin in this ticket for testing. Please review this PR(https://github.com/develar/app-builder/pull/120) again, and if there are no issues, merge it so we can release an alpha version. I'll integrate it into this ticket for testing.

**Comment by beyondkmp** [comment]
@mmaietta Please help rerun the failed job.

**Pull request merged**
