### PR TITLE
fix: add request.pause() to notification about progress

### PR DESCRIPTION
**Pull request by maczikasz**
See issue #1045

### CODE REVIEW

**Comment by develar** [comment]
cc @badams I think proper fix is to not listen `data`, but use `pipe` in the same way as we already use `progress-stream` for download.

**Comment by develar** [comment]
To be clear — I don't to use `progress-stream` here to reduce external deps. So, probably approach like our DigestTransform should be used here.

**Comment by maczikasz** [comment]
ok will take a look how it's done

**Comment by maczikasz** [comment]
@develar I pushed a new commit, did you mean like that?

**Comment by develar** [comment]
@maczikasz Thank you! 0.9.1 published with your fix.

**Comment by badams** [comment]
@develar @maczikasz Nice work, this is a much cleaner solution 👍

**Pull request merged**
