### PR TITLE
feature: specification of signing algorithms

### PR DESCRIPTION
**Pull request by heinzbeinz**
added options for windows signing: signingHashAlgorithms (sha1, sha256) and signcodePath (path to signtool.exe)

**note**: sha256 only signing works only in conjunction with pull request for signcode-tf

### CODE REVIEW

**Comment by develar** [comment]
> signcodePath

I don't like it. It is ok for low-level tool `signcode`, but not for electron-builder. Maybe env option is suitable for you? Like `SIGNTOOL_PATH`? Or do you add this param to use osslsigncode on Linux? In this case `USE_SYSTEM_SIGNCODE` will be added.

**Comment by heinzbeinz** [comment]
Thanks for your feedback. I used it in Windows Server 2008, The bundled signtool seems to new for this windows edition (looks like from Windows 10 SDK). An SIGNTOOL_PATH would be perfectly fine.

**Comment by develar** [comment]
@heinzbeinz Send me your version of signtool and I will test it — as solution of https://github.com/electron-userland/electron-builder/issues/416 we can just downgrade signtool if it passes tests for win10.

**Comment by heinzbeinz** [comment]
Here you go. (exe could not be directly uploaded, I wrapped it in a zip)
[signtool.zip](https://github.com/electron-userland/electron-builder/files/279718/signtool.zip)

**Comment by heinzbeinz** [comment]
Closing because of #435

**Pull request closed without merging**
