### PR TITLE
feat: use 7za to produce Squirrel.mac zip (smaller size — the same ti…

### PR DESCRIPTION
**Pull request by develar**
…me to compress)

Also, add compression option to set compression level in one place (currently, only Linux and OS X supported)

### CODE REVIEW

**Comment by asethwright** [comment]
Is there a dependency requirement for 7za I'm missing? I am getting errors on my build.

```
Packaging app for platform darwin x64 using electron v0.37.3
App is not signed: CSC_LINK or CSC_NAME are not specified
Creating DMG
Creating ZIP for Squirrel.Mac
.../node_modules/electron-builder/vendor/osx/7za: line 1: version: command not found
.../node_modules/electron-builder/vendor/osx/7za: line 2: oid: command not found
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/size: 1667792: No such file or directory.
```

**Comment by asethwright** [comment]
I tried `brew install p7zip`

```
which 7za
/usr/local/bin/7za
```

Will be glad to open an issue if needed. Thanks for your time. This makes building so easy.

**Comment by develar** [comment]
@asethwright https://github.com/electron-userland/electron-builder/issues/296

**Comment by asethwright** [comment]
Ah, thanks!

**Pull request merged**
