### PR TITLE
Make a setting for --build-from-option flag

### LINKED ISSUE #787: Install app deps always trigger rebuild
* **Version**: 7.10.0

* **Target**: Mac and Linux

Hello, I'm using electron-builder with native module (https://github.com/lyssdod/node-libtorrent). The module itself uses `node-pre-gyp` and has precompiled binaries. It installs flawlessly if I'm not using `electron-builder` directly (running `npm install` from `app` directory works). But if I do, it fails with

```
Error output:
module.js:457
    throw err;
    ^

Error: Cannot find module 'adm-zip'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

The fun fact is, this module (`adm-zip`) is specified in `node-libtorrent-ng`s `devDependencies` and is handled by regular `npm install` just fine. 

So my questions are:
1. Why `electron-builder` ignores default action of `node-gyp-rebuild` despite binaries are available?
2. Is there a way to debug 'install-app-deps' step?

Thanks!

### PR DESCRIPTION
**Pull request by lyssdod**
This seems to fix #787 

The only place I'm unsure of is (haven't touched yet):
https://github.com/electron-userland/electron-builder/blob/a4eeaded7a7e0da77112a1c96786d80f90e47083/src/install-app-deps.ts#L33

### CODE REVIEW

**Comment by lyssdod** [comment]
My main concern for this — I have to create installers for all platforms, but I have only one (Mac) available. Since I won't be able to rebuild my native modules with MSVC on Mac, I would like to use already present precompiled binaries for bundling

**Comment by jordansteeves** [comment]
Hi! Any word on a review here? @develar

**Comment by develar** [comment]
Did you investigate why https://github.com/electron-userland/electron-builder/issues/647 doesn't work? I mean — why " it uses prebuilt to download native binary instead of compiling."? Why incorrect  binaries was used? 

I don't want to introduce yet another flag, it is better to investigate — is it really bug in the precompiled binaries.

**Comment by lyssdod** [comment]
@develar I`ll try to investigate 5.22.2 release

**Comment by develar** [comment]
@lyssdod Issues is not in the electron-builder, should be reproducible using latest version also.

**Comment by lyssdod** [comment]
The trick is in the `--build-from-source` flag which's being handled by `node-pre-gyp` and forces compilation instead of checking for binaries. In my particular case compilation fails because I've moved all compilation deps to `devDependencies` to minimize final package size (for fast `npm install` which will install only needed stuff). Moving these deps back to `dependencies` eliminates the benefits of using  `node-pre-gyp` completely, because this way it will compile the code for one particular platform (host platform `electron-builder` is running at), but not for others.

**Comment by develar** [comment]
@lyssdod I understand you completely. But I want to understand — does `node-pre-gyp` works correctly or not. Bug #647 was reproduced by me — incorrect precompiled binaries were used. It is very, very critical — because you cannot test your app on all platforms and archs every release.

So, I ask you to check — is it `node-pre-gyp` bug or not. Who is guilty :) To ensure, that your approach really works and correct binaries will be used in ALL cases.

If you don't want to do this work, I can accept PR but this flag will be not documented and marked as experimental. And not by default.

**Comment by lyssdod** [comment]
I'm all up for solving this issue on the `node-pre-gyp`'s side, it just seems to me that they're not very active and responsive to issues (in contrast to you :+1: ): https://github.com/mapbox/node-pre-gyp/issues/239

I`ll look into bug #647 more thoroughly now.

**Comment by lyssdod** [comment]
Hi again @develar,

I've looked into #647 but didn't see any useful info there (release used there already has this flag enabled). Instead I've prepared a test repo which uses prebuilt modules after patching `electron-builder`:

https://github.com/lyssdod/electron-abi-test


> I don't want to introduce yet another flag

http://electron.atom.io/docs/tutorial/using-native-node-modules/ says there's another method of specifying it: 
```shell
# Tell node-pre-gyp to build module from source code.
export npm_config_build_from_source=true
```

I can update PR to handle this option instead of handling the flag if it makes sense.

**Comment by develar** [comment]
@lyssdod Ok, thanks. 

> So in general it is recommended to always build native modules from source code.

For this flag will be not enabled by default, according to this note.

**Comment by lyssdod** [comment]
Thank you!

**Pull request merged**
