### PR TITLE
Auto update does not work on machines with Powershell version < 3

### LINKED ISSUE #1732: Auto update does not work on machines with Powershell version < 3
* **Version**:  LATEST 

* **Target**:  NSIS

The auto updater was changed to use "Convert-from-json" function which was introduced in powershell 3, so on windows 7 machines without powershell 3 it will not work. If that's intented we will need to adjust our system requirements, please tell me if there is a way to make it backward compatible.

Thanks

### PR DESCRIPTION
**Pull request by MariaDima**
Close #1732

### CODE REVIEW

**Comment by MariaDima** [comment]
I was experimenting with ConvertTo-CSV command that is supported by powershell < 3.

It could be used to support Windows 7 users.
However, the output is not good at all: It's more like a string, from which we need to extract data using either a regular expression or a substring logic (easier).

What's your thoughts on this?
The output could depend on the way the certificate was created (which options were provided during creation), but it could be an attempt to support more users before bypassing verification.

**Comment by develar** [comment]
Why not just check windows version?

**Comment by develar** [comment]
Thanks!

**Comment by develar** [comment]
Until https://github.com/electron/electron/pull/9648 is not accepted, code signing doesn't matter at all and users in any case not protected.

**Pull request closed without merging**
