### PR TITLE
fix(mac): Workaround for hdiutil randomly failing (#5431)

### PR DESCRIPTION
**Pull request by chokladmal**
For some but not all Mac users building dmg files often fails.

After some investigations the cause seems to be that `hdiutil create` (when being run to create a temporary dmg file in createStageDmg) fail when trying to unmount the created volume due to "resource busy". As this only affects some Macs it seems to be caused by something on those machines. Suggested is antivirus software but that's not confirmed.

It turns out that after retrying the `hdiutil create` command a few times it usually succeeds and this workaround is based on that idea - to simply retry the command up to five times before throwing and failing the build. This does not fix the real issue!

Tracking issue: https://github.com/electron-userland/electron-builder/issues/5431

### CODE REVIEW

**Review by mmaietta — CHANGES_REQUESTED** [review]
I'm not sure on what could be the actual solution here, as the random failures seem to be more OS-related from what I've searched and my personal experience.

As an improvement here, I'd recommend using `builder-util` `retry<T>` function. 
https://github.com/electron-userland/electron-builder/blob/master/packages/builder-util/src/util.ts#L384
Just need to export it and it simplifies all your usage to 2 lines. 

Related notes: This may be misusing the logger's debug flag, but you could also conditionally add `-debug` since the retry function doesn't have any explicit logging info. I also increased duration to 1s as sometimes I had to wait that long before a retry when I had my own hdiutil bash scripts

```
if (log.isDebugEnabled) {
  imageArgs.push("-debug")
}
await retry(spawn("hdiutil", imageArgs), 5, 1000)
return tempDmg
```

**Comment by BelinChung** [comment]
It seems to be the problem caused by this line
```
// imageArgs.push("-fs", "HFS+", "-fsargs", "-c c=64,a=16,e=16")
```
When I commented it out, the dmg package was successfully built on Big Sur.

**Comment by mmaietta** [comment]
Out of curiosity, can you try just omitting the `-fsargs < >`? I'm wondering if all we need is
```
imageArgs.push("-fs", "HFS+")
```

From the man:
```
-fsargs newfs_args
                          additional arguments to pass to whatever newfs pro-
                          gram is implied by -fs.  newfs_hfs(8) has a number
                          of options that can reduce the amount of space
                          needed by the filesystem's data structures.  Sup-
                          pressing the journal with -fs HFS+ and passing argu-
                          ments such as -c c=64,a=16,e=16 to -fsargs will min-
                          imize gaps at the front of the filesystem, allowing
                          resize to squeeze more space from the filesystem.
                          For truly optimal filesystems, use makehybrid.
```

**Comment by chokladmal** [comment]
Thank you for your comments! I really appreciate that you're helping out with this :)
As I mentioned in the issue thread I've tried running hdiutils with -attach with some success. It doesn't fail but it will have to be unmounted at a later stage instead. Right now I have somewhat limited time but I will keep trying, especially the suggested changes to the args.

**Comment by lutzroeder** [comment]
@chokladmal did you track down the actual error by running with `export DEBUG_DMG=true` and repro by running this command in isolation. Which version of electron-builder and macOS are you running and does the Terminal have full disk access? This seems to be a bit too much "no idea why this is happening but a for loop might hide it"? Is there some effort to diagnose the underlying issue and drive a fix?

**Comment by chokladmal** [comment]
@lutzroeder I saw that you had already commented in the issue but for the record it's this one https://github.com/electron-userland/electron-builder/issues/5431

I'm running electron-builder 22.9.1 and macOS Catalina 10.15.17

In https://github.com/electron-userland/electron-builder/issues/5431 we've narrowed it down to hdiutil failing due to "resource busy" when hdiutil create tries to unmount the volume.

**Comment by chokladmal** [comment]
> Out of curiosity, can you try just omitting the `-fsargs < >`? I'm wondering if all we need is
> 
> ```
> imageArgs.push("-fs", "HFS+")
> ```
> 
> From the man:
> 
> ```
> -fsargs newfs_args
>                           additional arguments to pass to whatever newfs pro-
>                           gram is implied by -fs.  newfs_hfs(8) has a number
>                           of options that can reduce the amount of space
>                           needed by the filesystem's data structures.  Sup-
>                           pressing the journal with -fs HFS+ and passing argu-
>                           ments such as -c c=64,a=16,e=16 to -fsargs will min-
>                           imize gaps at the front of the filesystem, allowing
>                           resize to squeeze more space from the filesystem.
>                           For truly optimal filesystems, use makehybrid.
> ```

I've tried it. At first it seemed to be working but it finally failed with the same 
```

DIHLDiskImageCreate() returned 49168
hdiutil: create failed - Resource busy
```
after ten or so tries.

**Comment by mmaietta** [comment]
This should be fixed (from a PR revert) in the latest prerelease cut `22.10.4`

**Comment by lutzroeder** [comment]
@mmaietta this might be a different issue? The reverted PR was a recent change and repros reliably. This issue sounds like it succeeds on retry, shows a different error and also happened on previous versions? Next steps are probably either finding a reliable repro and tracking down why this is happening.

**Comment by chokladmal** [comment]
If it is antivirus or something else maybe having something imitating that
behaviour? A script opening files on the volume as soon as it's mounted and
files are added could perhaps trigger the problem. I can try it out once
I'm back at my company laptop after the holidays.

**Comment by lutzroeder** [comment]
@chokladmal, yes, the goal is to root cause the issue, less how we can recreate a behavior that would require adding a retry approach to the build pipeline. Masking fragile behavior that isn't well understood tends to lead more fragile and unpredictable behavior. For example, if this is caused by a virus scanner, the right fix is probably to suspend the scanner during build, add an exclusion or work with the vendor. If the issue is a bug in `hdiutil` the right fix would be fixing `hdiutil`.

**Comment by shrpne** [comment]
@lutzroeder can it be released as a workaround to fix current issue and then be replaced with real fix, when it ready?

Because for now there is no workaround. I even can't install chokladmal's fork because it is monorepo. And since it is typescript it requires a lot of tooling to apply his patch to my own project.

I see no problems with releasing it. It should not cause performance issues or bugs to other users. The only problem with it, it is not beautiful, but it works.

**Comment by mmaietta** [comment]
@shrpne here's a script that @lutzroeder put together for compiling any branch and patching the results. Run from your current app directory (with electron-builder one dir up. You can adjust paths as needed)
```
#!/bin/bash

pushd ../electron-builder
yarn compile
popd

rsync --recursive ../electron-builder/packages/app-builder-lib/out/ ./node_modules/app-builder-lib/out/
rsync --recursive ../electron-builder/packages/app-builder-lib/electron-osx-sign/ ./node_modules/app-builder-lib/electron-osx-sign/
rsync --recursive ../electron-builder/packages/builder-util/out/ ./node_modules/builder-util/out/
rsync --recursive ../electron-builder/packages/dmg-builder/out/ ./node_modules/dmg-builder/out/

cp ../electron-builder/packages/app-builder-lib/scheme.json ./node_modules/app-builder-lib/scheme.json

yarn patch-package app-builder-lib
yarn patch-package builder-util
yarn patch-package dmg-builder
```

**Comment by lutzroeder** [comment]
@shrpne not my call. This is an open source project so the challenge isn't shipping workarounds. The question is more who would own getting to the bottom of this and drive the right fix.

**Comment by lutzroeder** [comment]
@mmaietta the script looks like it got merged from different sources. Why is `patch-package` is needed?

**Comment by mmaietta** [comment]
@lutzroeder `patch-package` allows changes to be persisted in the project repo as a `.patch` file to save your local changes.

**Comment by shrpne** [comment]
@mmaietta thank you for sharing this script, but it still looks pretty complicated, as I understand it is can't be used as a drop-in solution.

@lutzroeder honestly I don't understand, why opensource project can't accept temporary workaround, while waiting for real fix, which then will replace this workaround. 
From my point of view, working opensource project with temporary workaround is better than temporary not working opensource project without workarounds.

**Comment by lutzroeder** [comment]
@shrpne sure, not arguing that and it’s not my call to make for this repo. Why not come up with the real fix now? Are you signing up to get to the bottom of this later? What is going to change to make this easier when folks are hitting the issue less often or in more random circumstances due to the workaround masking the real issue. I’m more asking why the problem isn’t better understood and what can be done about that. You are asking for the cheapest way to make it not your problem.

**Comment by jzybert** [comment]
Which version of electron will this be included in?

**Comment by mmaietta** [comment]
Please update to latest electron-builder@22.10.5

**Pull request merged**
