### PR TITLE
Revert "Codesign all binary-like files"

### LINKED ISSUE #5487: electron-builder 20.10.3 fails with Operation not permitted
* **Version**: 22.10.3
* **Electron Version**: 11.1.0
* **Target**: DMG
* **OS**: macOS Big Sur 11.1 (20C69)

**Repro steps**
1. `git clone https://github.com/electron/electron-quick-start.git`
2. `cd electron-quick-start`
3. `npm install --save-dev electron-builder@22.10.3`
4. `npm install`
5. `export DEBUG_DMG=true`
6. `npx electron-builder --mac`

```
~/electron-quick-start: npx electron-builder --mac
  • electron-builder  version=22.10.3 os=20.2.0
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=11.1.0 appOutDir=dist/mac
  • default Electron icon is used  reason=application icon is not set
  • signing         file=dist/mac/electron-quick-start.app identityName=*** identityHash=*** provisioningProfile=none
  • building        target=macOS zip arch=x64 file=dist/electron-quick-start-1.0.0-mac.zip
  • building        target=DMG arch=x64 file=dist/electron-quick-start-1.0.0.dmg
  • building embedded block map  file=dist/electron-quick-start-1.0.0-mac.zip
  ⨯ hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:

Output:
Initializing…
Creating…
Copying…
could not access /Volumes/electron-quick-start 1.0.0/electron-quick-start.app/Contents/Resources/.BC.T_OYJ2t1 - Operation not permitted
Finishing…
```

This regressed starting with #5322.

Related #5465 #5431

@adam-lynch @develar

### PR DESCRIPTION
**Pull request by lutzroeder**
Revert electron-userland/electron-builder#5322

Fix #5487

@adam-lynch @develar

### CODE REVIEW

**Review by mmaietta — APPROVED** [review]

**Comment by lutzroeder** [comment]
Test failure is unrelated to this change. See #5426.

**Comment by develar** [comment]
@lutzroeder If we revert, what's alternative? Maybe you can add more patterns to codesign to solve initial issue? I mean if original fix was intended to fix code signing of some files, let's just add such patterns. Because I cannot simply revert.

**Comment by lutzroeder** [comment]
@develar Hello World regressed in 22.10.3 due to this change so we should start by reverting the change. I'm not an expert what the issues are with special cases involving signing native modules nor did the original pull request include an exact repro. The goal for this pull request is to undo the regression from 22.9.1 to 22.10.3.

#5465 is tracking one investigation for native modules. Maybe we should use that ticket to drive a better fix?

@mmaietta @gnattu @adam-lynch

**Comment by mmaietta** [comment]
@develar thanks for merging.

https://github.com/electron-userland/electron-builder/pull/5493
I gave another swing at this for detecting binary files, however, I don't have a repo or exact description from the original #5322 PR on what else to test specifically for. It works locally in my projects but that's still limited

**Pull request merged**
