### PR TITLE
feat: adding dot asar option

### PR DESCRIPTION
**Pull request by markgardner**
This will allow users to have the ability to include dot folders into their asar file. This should maintain existing default functionality.

### CODE REVIEW

**Comment by develar** [comment]
Could you please specify the reason why you have to do it? Name of required files? My plan is to get feedback and add explicit inclusion for such files (name starts with dot).

**Comment by markgardner** [comment]
We just keep our built files in a .build folder. It helps us keep the app directory clean when building locally

**Comment by develar** [comment]
If I understand correctly — you build source js using Babel/TS to dir `.build`? Hmm.... You also have to modify `files` option, because dot files are ignored as well by default.

Ok, it seems yor setup is not common and it cannot be automatically discovered. Or maybe is there some way — field in the package.json, Babel config?

**Comment by markgardner** [comment]
We have a homegrown asset management tool that is like webpack. We use that to create all of the minified release files.

We are doing a few custom things to build all of our assets that is definitely an edge case. We did modify the files array to include our build folder (that seemed pretty straight forward to me once I released how glob ignores dot folders by default).

Side Note, I started from scratch upgrading our complex build process for 0.36.0 that would call electron-packager directly. Using electron-builder is sooo much easier. Thank you for all you have done with this.

**Comment by develar** [comment]
Please be aware that you should not just add pattern `**/.*`, you should add pattern `.build`. To ignore `node_modules/.bin`, `. DS_Store` and so on.

**Pull request merged**
