### PR TITLE
feat: configurable electron-builder-binaries host

### PR DESCRIPTION
**Pull request by nekator**
introduce environment variables to configure where the electron-builder-binaries are downloaded from.

related to electron-userland/electron-builder-binaries#21 and #1859

### CODE REVIEW

**Comment by nekator** [comment]
Hi @develar,

fist of all i want to thank you for your work ;)
It would be great if you could take a look at this PR and give me any feedback.

**Comment by develar** [comment]
Sorry for delay, merged.

**Comment by nekator** [comment]
Thanks for your response and for merging my PR.

**Comment by Paul-HIT** [comment]
Thanks for your contributions on configurable electron-builder-binaries host. The feature is fit for me.

**Pull request merged**
