### PR TITLE
feat(nsis): KeepShortcuts mechanism is not functional

### LINKED ISSUE #2084: KeepShortcuts mechanism is not functional
* **Electron-Builder Version**: 19.28.4

* **Electron-Updater Version**: 2.8.9

* **Target**: Windows

If a user decides to delete either the desktop or the menu shortcut (or both), his choice needs to be remembered.
The deleted shortcuts shouldn't be recreated with an application update.

Currently, the shortcuts are always recreated.
Only for the desktop shortcut there is an option to not create it, but this is a global configuration option (not a user customized selection).

I think we broke the functionality with a previous commit for https://github.com/electron-userland/electron-builder/issues/1917.

### PR DESCRIPTION
**Pull request by MariaDima**
Close #2084

### CODE REVIEW

**Comment by develar** [comment]
Will be published 22 September.

**Comment by develar** [comment]
Sorry that previous PR changes were aplied without your review.

**Comment by MariaDima** [comment]
No problem!
Is it possible to have a release sooner?

**Comment by develar** [comment]
No, i am on vacation.

**Comment by MariaDima** [comment]
Ok!
Have a good time! Enjoy your vacations!

**Pull request merged**
