### PR TITLE
fix: cannot parse blockmap when auto updating

### PR DESCRIPTION
**Pull request by sandeep1995**
This PR fixes the issue https://github.com/electron-userland/electron-builder/issues/4736

### CODE REVIEW

**Comment by sandeep1995** [comment]
@develar Can you review this PR and if possible release it as pre-release?

**Comment by Elementrat** [comment]
Looking forward to this!

**Comment by subh261096** [comment]
Looking forward to fix the issue with this PR.

**Comment by HaydnDias** [comment]
Came across this the other day, glad to see there's a fix for it, look forward to it being mainlined

**Comment by ramenski** [comment]
Looking forward to this fix

**Comment by VitruxPT** [comment]
This PR fixes issue #4736 
I will mark the issue as closed once this PR is merged.
Nicely done @sandeep1995!

**Comment by SijieCai** [comment]
@VitruxPT  Can anyone merge this

**Comment by VitruxPT** [comment]
> @VitruxPT Can anyone merge this

@SijieCai, as much as I would like to merge it myself I don't have permission to do so, so we'll have to wait a little longer.

**Comment by bence04** [comment]
@VitruxPT  what do you think, when it will be merged?

**Pull request merged**
