### PR TITLE
feat: Adding download-progress event to AutoUpdater

### PR DESCRIPTION
**Pull request by badams**
Adding a new event `download-progress` to the AutoUpdater, can be used like so

```js
autoUpdater.addListener("download-progress", (e, progress) => {
    console.log(progress.percent);
});
```

payload received from this event is as follows:

```
{
    bytesPerSecond: 6365261,
    percent: 20.95,
    total: 61289092,
    transferred:12838731
}
```

#958 #948

### CODE REVIEW

**Comment by badams** [comment]
Sorry my two PRs might not meet the guidelines, I didnt see that initially

**Comment by badams** [comment]
@develar I've fixed the conflicts and added a test for this feature, is there anything else I need to do to get this merged?

**Comment by develar** [comment]
@badams Thanks for complete PR with test. Merged.

**Comment by develar** [comment]
electron-auto-updater@0.8.5 published with this great feature.

**Comment by joshuapinter** [comment]
Hey Guys. This might be a dumb question but does this work with Electron's native [autoUpdater](https://electronjs.org/docs/api/auto-updater)? We're using `electron-forge` and the following does not emit any events:

```js
autoUpdater.on('download-progress', (progressObj) => {
  let log_message = "Download speed: " + progressObj.bytesPerSecond;
  log_message = log_message + ' - Downloaded ' + progressObj.percent + '%';
  log_message = log_message + ' (' + progressObj.transferred + "/" + progressObj.total + ')';
  console.log( log_message );
})
```

Just curious if this is `electron-builder` specific. 

Thanks!

**Comment by badams** [comment]
@joshuapinter no this is a custom feature in electron-builder

**Comment by joshuapinter** [comment]
@badams Thanks so much for the quick reply! Hell of a custom feature! Might be worth switching over at some point. :)

Thanks again!

**Comment by hmpargi** [comment]
> Hey Guys. This might be a dumb question but does this work with Electron's native [autoUpdater](https://electronjs.org/docs/api/auto-updater)? We're using `electron-forge` and the following does not emit any events:
> 
> ```js
> autoUpdater.on('download-progress', (progressObj) => {
>   let log_message = "Download speed: " + progressObj.bytesPerSecond;
>   log_message = log_message + ' - Downloaded ' + progressObj.percent + '%';
>   log_message = log_message + ' (' + progressObj.transferred + "/" + progressObj.total + ')';
>   console.log( log_message );
> })
> ```
> 
> Just curious if this is `electron-builder` specific.
> 
> Thanks!

did you able to fix this? 
I am trying to track the progress of download too.. thanks

**Comment by joshuapinter** [comment]
@hmpargi We built our own custom downloader with electron-forge. Then months later we ended up switching the project to electron-builder.

**Pull request merged**
