### PR TITLE
Feat: customize nsis binaries using NSIS options

### PR DESCRIPTION
**Pull request by shaluyadav13**
Using customNsisBinary option we can add customized binaries url, checksum and version(optional).
When version is not provided but both url and checksum is provided, then version will be first 8-digits of checksum(unique).

Please let me know in case of any concerns.

### CODE REVIEW

**Comment by shaluyadav13** [comment]
@develar Any update on this will be really appreciated. Thanks!

**Comment by mmaietta** [comment]
@shaluyadav13 can you please resolve the merge conflicts? I can review afterward

**Comment by mmaietta** [comment]
@shaluyadav13 , do you mind if I pick up this PR?

**Comment by shaluyadav13** [comment]
> @shaluyadav13 , do you mind if I pick up this PR?

@mmaietta Sure.

**Comment by mmaietta** [comment]
Incorporated into https://github.com/electron-userland/electron-builder/pull/6024

**Pull request closed without merging**
