### PR TITLE
feat: Add directory prompt page in boring installer

### PR DESCRIPTION
**Pull request by domachine**
This is a quick n dirty change which works for me. I just wanted to keep these changes in this pull-request to elaborate and discuss on it. Regard this as a starting point to solve #596. Still lacking are e.g. tests, of course.

### CODE REVIEW

**Comment by domachine** [comment]
@develar Should I introduce an option to disable this page?

**Comment by develar** [comment]
Yes, I think,  we should not promote it and so, do not use it by default.

Proposed option: `customizableInstallationDirectory`. Defaults to `false`.

**Comment by domachine** [comment]
:+1:

**Comment by develar** [comment]
Usually I don't bother pull request author and make all required changes myself, but if you want to prepare merge-ready PR — that's great :)

**Comment by domachine** [comment]
@develar I'd love to :)

**Comment by noahbenham** [comment]
What's the status of this? I could really use this ability.

**Comment by develar** [comment]
@noahbenham Option should be added, please see https://github.com/electron-userland/electron-builder/pull/909#issuecomment-260896103

**Comment by domachine** [comment]
Hey, sorry I've been so busy since I started this PR. Hope to find some time this evening.

**Pull request closed without merging**
