### PR TITLE
Allow customization of bundleIdentifier for the new Electron 6+ renderer processes

### PR DESCRIPTION
**Pull request by aguynamedben**
Addresses https://github.com/electron-userland/electron-builder/issues/4691

Allow customization of `bundleIdentifier` for the new Electron 6+ renderer processes. This change addresses backward-compatibility issues arising from the Electron 6 renderer process name change ([learn more](https://www.electronjs.org/blog/electron-6-0#electron-helper-rendererapp-electron-helper-gpuapp-and-electron-helper-pluginapp)). Without this, upon upgrading to Electron 6+ and building your app, macOS sees the renderer process as having a different `bundleIdentifier` than it saw before.

**Default `bundleIdentifier` values for Renderer process**
Electron 5 and before: `com.acme.CoolApp.helper`
Electron 6+: `com.acme.CoolApp.helper.Renderer`

macOS uses `bundleIdentifier` for things like keychain accesses, so apps that previously accessed things in macOS using the value `com.acme.CoolApp.helper` need to be able to keep that `bundleIdentifier` for their Electron renderer process.

Example usage in my app is:
```
"helperBundleId": "io.hypertools.Command-E.helperGeneric",
"helperRendererBundleId": "io.hypertools.Command-E.helper",
```

This maintains the `bundleIdentifier` value across Electron 5 and Electron 6+.

The real-world issue for app was this: In a new version of our app, our users saw a macOS permission dialog for every single `keytar.get()`. macOS was not trusting our renderer process because the `bundleIdentifier` had changed.

### CODE REVIEW

**Comment by aguynamedben** [comment]
@develar I'm working on this more... how many versions back of Electron must the current electron-builder support? I'm looking at options like [this](https://github.com/electron-userland/electron-builder/pull/4692/files#diff-332d71e64017661fb6f3699af2d56323R89) that were deprecated in January 2018.

Also, would it be bad to drop support for Electron 4 support? The current version is Electron 8, and as a user of Electron from Electron 3 (?) I've always found upgrading Electron to be fairly straightforward.

**Comment by develar** [comment]
Supporting v5+ only is ok. Just major version of electron builder will be
released.

**Comment by aguynamedben** [comment]
@develar This is ready for review. I updated the PR description to make it more clear why I added this. It looks like there was probably some history with `helperBundleId` needing to be specified. This PR allows power users to customize the `bundleIdentifier` for Helpers as they need, but still provides good defaults for new users of electron-builder.

It should work across all version of Electron, and it's backward compatible (no breaking changes).

Let me know if there's anything else I can do to help get this merged!

**Comment by aguynamedben** [comment]
I'm hoping this can be merged, is there any reason it's not likely to be merged? It's backwards-compatible, uncomplicated, and really just provides a config variable that was already available—setting the bundleId of the renderer—in a way that works with Electron 6+.

I understand you're extremely busy, I just want to understand if this is likely to be merged. We're in no rush, we have a branch working on a local machine, but given the compiled nature of electron-builder it'd be nice to have these config values in a compiled, packaged version out there the rest of my team can trust.

I appreciate your work. Oh yeah, we just donated!!! (Command E) 🙏

**Comment by develar** [comment]
Before merge I have to release a new version to mark it a production ready (https://github.com/electron-userland/electron-builder/releases/tag/v22.3.6). And then release another version with this change as pre-release.

**Comment by develar** [comment]
Thanks a lot of for this improvement, it moves electron-builder forward.

**Comment by develar** [comment]
22.4.0 was released.

**Comment by aguynamedben** [comment]
Thanks @develar, you rock 💪

**Pull request merged**
