### PR TITLE
feat(electron-updater): follow `autoInstallOnAppQuit = false` on macOS

### PR DESCRIPTION
**Pull request by MortalKastor**
Make `electron-updater` on macOS behave like other OSes regarding the `autoInstallOnAppQuit` flag by cheating a bit around Squirrel.Mac limitation of not being able to *not* apply an update after it has downloaded it.

I tried to make my changes as minimal as possible, and took advantage of the fact that `electron-updater` already downloads the update by itself first and only expose said update to Squirrel in a second time. The trick here is to only trigger Squirrel when we want to apply an update rather than after a successful download.

This PR succeed and replace the previous #3745 which was targeting an out of date version of `electron-builder`. The logic of both is more or less the same, but the implementation differs because of the change of `quitAndInstall()` method from `async` to sync.

### Context
This feature is required for our app ([Ledger Live](https://github.com/LedgerHQ/ledger-live-desktop)) to be able to do an additional cryptographic check on downloaded files and conditionally abort the update on a failed verification.

### CODE REVIEW

**Comment by gre** [comment]
@develar any chance to take a look at this? Thanks a lot.

**Comment by gre** [comment]
@develar any chance we can help you on testing this / provide you more information for this PR? Thanks

**Comment by gre** [comment]
We are keeping the PR up to date, it would really be great if this bugfix could go to upstream.

**Comment by gre** [comment]
hell yeah it's relevant.

**Comment by gre** [comment]
yes...

**Comment by gre** [comment]
😭

**Comment by gre** [comment]
re-open please?

**Comment by mahnunchik** [comment]
@develar ping

**Comment by bjbk** [comment]
Wonder why this is taking over a year to implement?  🤔

**Comment by mmaietta** [comment]
Merged the rebased PR #5271 
If any further comments are needed, please consolidate follow-ups in that PR or in a new issue, thanks!

**Pull request closed without merging**
