### PR TITLE
feat(mac): support macos signature additionalArguments parameter 

### PR DESCRIPTION
**Pull request by PBK-B**
Update [electron/osx-sign](https://github.com/electron/osx-sign), add macos signing option `additionalArguments`.
https://github.com/electron/osx-sign/pull/316
https://github.com/electron/osx-sign?tab=readme-ov-file#signing-with---deep

@develar @mmaietta TBR;

### CODE REVIEW

**Comment by mmaietta** [comment]
Thanks for your contribution! Could you please update electron/osx-sign package as part of the PR? Looks like we're pinned to 1.0.5

**Comment by PBK-B** [comment]
Oh, damn it, I forgot to submit the package.json file. Thank you for reminding me @mmaietta

**Comment by PBK-B** [comment]
Due to the higher pnpm version of the local environment, the pnpm-lock.yaml file has been greatly changed, so I choose to ignore the submission of the file (thus may lead to the failure of ci). If there is anything that can help, I can cooperate.

**Comment by mmaietta** [comment]
I gotcha. Updated the pnpm-lock.yaml and added a changeset

**Pull request merged**
