### PR TITLE
Fixed wrong version (0.0.0 to 19.5.1)

### PR DESCRIPTION
**Pull request by black-snow**

### CODE REVIEW

**Comment by black-snow** [comment]
Fixes https://github.com/electron-userland/electron-builder/issues/1816

**Comment by black-snow** [comment]
Missing dep `electron-webpack` --- also seing this in latest `master` when `yarn test`.

**Comment by develar** [comment]
Thanks, but problem is different — this version was released not correctly — `set-versions` was not called before `compile`.

**Comment by black-snow** [comment]
Alright. I already thought that you don't manually set them each time ;)

**Pull request closed without merging**
