### PR TITLE
start app on runAfterFinish when oneClick=false #5792

### PR DESCRIPTION
**Pull request by beliaev-maksim**
I suppose this should do a trick for #5792

### CODE REVIEW

**Comment by mmaietta** [comment]
Just to check, have you tested this? 🙃

**Comment by beliaev-maksim** [comment]
@mmaietta 
actually I did a wrong test, I forgot to exclude silent flag from my mainwin.js


how can I ensure that
pnpm compile and yalc push actually applied the change?
I see the message
`Pushing electron-updater@4.3.7 in C:\git\test\electron_ui`

however even if I comment macro 
`# !insertmacro MUI_PAGE_FINISH`
it still inserts finish page

**Comment by mmaietta** [comment]
That's odd indeed, as it shows up in my yalc folder. Maybe try using a force flag? `yalc push --replace`

Alternatively, you can manually copy that file over to the project node_modules location :`node_modules/app-builder-lib/templates/nsis/assistedInstaller.nsh`

**Comment by mmaietta** [comment]
@beliaev-maksim, would you happen to have a sample repo/gist for this functionality? I can try and pick this up

**Comment by beliaev-maksim** [comment]
@mmaietta 
since this involves update of the electron app, I assume we need a repo and releases.

For my tests I used dummy repo: https://github.com/beliaev-maksim/refactored-pancake 
and was creating version v1.0 and v2.0 to test (change version in https://github.com/beliaev-maksim/refactored-pancake/blob/master/electron_ui/package.json)

potentially you can fork this one for tests, but you will need to change links in package.json
~~~
"publish": [
              {
                "provider": "github",
                "owner": "beliaev-maksim",
                "repo": "refactored-pancake"
              }
~~~

you can run `npm run deploy` from electron_ui folder

**Pull request closed without merging**
