### PR TITLE
Add Apple development as valid development cert

### PR DESCRIPTION
**Pull request by Hinton**
This PR adds support for the newer "Apple Development" certificates, mentioned in the [Xcode 11 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-11-release-notes).

> Xcode 11 supports the new Apple Development and Apple Distribution certificate types. These certificates support building, running, and distributing apps on any Apple platform. Preexisting iOS and macOS development and distribution certificates continue to work, however, new certificates you create in Xcode 11 use the new types. Previous versions of Xcode don’t support these certificates. (45527608)

### CODE REVIEW

**Comment by buu700** [comment]
"Apple Distribution" is also missing as a valid alternative to "3rd Party Mac Developer Application".

**Comment by Hinton** [comment]
@buu700 Good point, I've added "Apple Distribution" as an alternative when signing mas.

**Review by mmaietta — APPROVED** [review]

**Comment by mmaietta** [comment]
Nice work! Any chance you'd be willing to open a PR on `docs` branch for updating our Documentation too? :) 
https://www.electron.build/code-signing#how-to-export-certificate-on-macos

**Comment by Hinton** [comment]
@mmaietta Thanks for merging it. I can look into updating the docs sometime next week.

**Comment by gaodeng** [comment]
🙏  Thanks, that's great. 
When will the update be pushed to npm?

**Comment by gaodeng** [comment]
@develar @mmaietta

**Pull request merged**
