### PR TITLE
feat(msi): support assisted installer for MSI target

### PR DESCRIPTION
**Pull request by aplum**
Add basic support for assisted installer, with UI to choose between per-user and per-machine. Supported config options: runAfterFinish, perMachine, oneClick. Not supported: license (EULA), allowToChangeInstallationDirectory, etc.

The UI dialogs are WelcomeDlg -> InstallScopeDlg -> VerifyReadyDlg. For `perMachine=true`, InstallScopeDlg doesn't allow changing the scope. Starting with the useless WelcomeDlg instead of going straight to InstallScopeDlg allows us to reuse an existing dialog set (WixUI_InstallDir) to reduce the custom code here, and makes it easier to add/remove dialogs if more features are supported in the future (EULA, allowToChangeInstallationDirectory).

I've tried to match the behaviour of NSIS for the supported config options based on what I came across in docs/PRs/issues.

This also prevents oneClick's runAfterFinish from executing when installed silently, because that's probably never desired (see [Rocket.Chat.Electron #1839](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1839)).

I've tested upgrading from the existing oneClick MSI to this PR's oneClick and assisted MSIs (for both per-user and per-machine), and it worked in all cases, including when the installation directory is different (due to [this line](https://github.com/aplum/electron-builder/blob/089c4e5ffcc9636d62e98307c23481d7ac79060a/packages/app-builder-lib/src/targets/MsiTarget.ts#L175) changing to match NSIS). GPO installs also work.

### CODE REVIEW

**Comment by mmaietta** [comment]
Thank you for your contribution!
Re:
>Supported config options: runAfterFinish, perMachine, oneClick. Not supported: license (EULA), allowToChangeInstallationDirectory, etc.

It seems like we need to add a new top-level entry `msi` to provide these supported config options (similar to the `nsis` top-level key @ https://www.electron.build/configuration/nsis) as they're not available under the default `win` entry. What are your thoughts?

>I've tried to match the behaviour of NSIS for the supported config options based on what I came across in docs/PRs/issues.

Also, thanks for pursuing this approach

**Comment by aplum** [comment]
I think that top-level key already exists from [this line](https://github.com/electron-userland/electron-builder/blob/bea51d6a8bb828d9b34734908f13b667aa55b0e9/packages/app-builder-lib/src/configuration.ts#L74). I've been using it in my projects and testing this PR. Those three options already exist under that key – runAfterFinish and perMachine already worked, and oneClick existed even though the resulting MSI didn't function quite correctly. Unless there's somewhere else it needs to go too?

**Comment by davej** [comment]
@aplum is it possible that these changes broke the ability to use a custom `APPLICATIONFOLDER` param? Recent versions of Electron Builder don't seem to work with `APPLICATIONFOLDER` anymore. See issue here: https://github.com/electron-userland/electron-builder/issues/7193

**Comment by aplum** [comment]
@davej Seems possible. I'd have to investigate, but in the meantime let's discuss in the issue you linked.

**Pull request merged**
