### PR TITLE
refactor: Add better typing support on AppUpdater as an event emitter

### PR DESCRIPTION
**Pull request by Nokel81**
- Helps with not having to look up the specific types for the events
  that are emitted

Signed-off-by: Sebastian Malton <sebastian@malton.name>

### CODE REVIEW

**Comment by mmaietta** [comment]
As much as I liked this addition, it breaks `pnpm generate-docs`, which is how we auto-deploy to our Documentation website. I'm working on finding a fix, but if none are found, then we'll need to revert this PR.

@Nokel81 If you're willing to help out, you can test locally with `pnpm generate-docs`

**Comment by Nokel81** [comment]
I can give it a shot

**Comment by Nokel81** [comment]
I don't know anything about `carthasis` or even the inner workings of `handlebars` but I think it is being tripped up by the first `/` of the string `module:/Users/nokel81/repos/electron-builder/node_modules/.pnpm/typed-emitter@2.1.0/node_modules/typed-emitter/index.TypedEventEmitter` which it is trying to parse as a type reference or something. Is this the first new packaged dependency in a while?

**Comment by mmaietta** [comment]
Yeah, it's rare that a new dependency is added. I have renovatebot manage dependencies we already use

I did a search and found `index.TypedEventEmitter` referenced in `scripts/jsdoc/out/updater/electron-updater.js` after `generate-docs`
```
/**
 * @extends module:/Users/michaelmaietta/Development/electron-builder/node_modules/.pnpm/typed-emitter@2.1.0/node_modules/typed-emitter/index.TypedEventEmitter
...
```

Even the js intellisense is barfing on reading that line
Screen Shot 2022-05-03 at 1 25 58 PM

**Comment by Nokel81** [comment]
Ah I see indeed. The project that I work on uses `mkdocs` instead so I don't have a lot of experience with packages this package use. I guess either we have to figure out how to get an `{@link ...}` to somewhere or I should rewrite the PR to not use that dependency.

**Comment by mmaietta** [comment]
I wonder if we can edit it in helpers.js, as I see we already do that for various IDs
https://github.com/electron-userland/electron-builder/blob/cfa41316348db1d9576a428bc096370fe9689958/scripts/jsdoc/helpers.js#L260-L262
https://github.com/electron-userland/electron-builder/blob/cfa41316348db1d9576a428bc096370fe9689958/scripts/jsdoc/helpers.js#L312-L317

**Comment by mmaietta** [comment]
Changing this:
https://github.com/electron-userland/electron-builder/blob/cfa41316348db1d9576a428bc096370fe9689958/scripts/jsdoc/helpers.js#L33
to be `catharsis.parse(it.replace(/.*node_modules\//, "module:")` fixes the compilation issue, but I'm not sure of the impact on how that'd look on the docs. The updated `.md` file shows 
```
<li><a href="#AppUpdater">.AppUpdater</a> ⇐ <code>module:typed-emitter@2.1.0/node_modules/typed-emitter/index.TypedEventEmitter</code>
```

**Pull request merged**
