### PR TITLE
docs: how to generate a token and export to travis and appveyor

### PR DESCRIPTION
**Pull request by rafajaques**
I had some trouble while trying to figure out how to properly set GH_TOKEN in Travis and AppVeyor.
So I decided to add some instructions in Wiki.

### CODE REVIEW

**Comment by develar** [comment]
Thanks for your contribution, docs is very important.

We recommend to use UI to add env on CI. https://github.com/electron-userland/electron-builder/wiki/Code-Signing#travis-appveyor-and-other-ci-servers (step 3 "Set CSC_LINK and CSC_KEY_PASSWORD"). I think, we should merge this info and extract it to a new document.

**Comment by rafajaques** [comment]
What do you suggest?
Creating a page for CI servers?

**Comment by develar** [comment]
> What do you suggest?

I suggest to extract information how to set env using UI from Code-Signing to separate page (create new page). And add link to such page to Publishing Artifacts page.

**Comment by rafajaques** [comment]
I exported GH_TOKEN in Travis UI and everything went fine.
But in Appveyor it didn't work. It seems that the variable was not exported.
Any tips on that? Or should we use "encrypt data" in Appveyor?

**Comment by develar** [comment]
@rafajaques "In case of AppVeyor, don't forget to click on lock icon to “Toggle variable encryption”.

**Comment by rafajaques** [comment]
Isn't that so?

captura de tela 2016-06-21 as 13 38 46

**Comment by develar** [comment]
@rafajaques Should be ok. Please open issue and attach log, clarify "it didn't work".

**Comment by rafajaques** [comment]
I'm rebuilding to see if it works.

**Comment by rafajaques** [comment]
Nevermind. It was a problem related to publishing windows --ia32 and --x64 at the same time.
Now that I have everything setup, I'll be back to docs.

**Comment by jwheare** [comment]
FWIW, I ended up writing a very similar version of these docs (with more code signing specifics) for our project here: https://github.com/irccloud/irccloud-desktop/blob/master/docs/OfficialBuilds.md

**Pull request closed without merging**
