### PR TITLE
chrore: Add `repository.directory` to packages `package.json`

### PR DESCRIPTION
**Pull request by cawa-93**
This will allow various bots (as a renovate) to correctly find changelogs in the monorepos.

### CODE REVIEW

**Comment by mmaietta** [comment]
OMG yes, thank you.

**Review by mmaietta — APPROVED** [review]

**Review by mmaietta — APPROVED** [review]

**Comment by mmaietta** [comment]
Btw, do you have any advice/pro-tips on how to set up an automatic changelog generator for releases with github actions? I think this `repository.directory` was a prerequisite for configuring those.

**Comment by cawa-93** [comment]
>  do you have any advice/pro-tips on how to set up an automatic changelog generator for releases with github actions?

@mmaietta I don't think so. For my last pet-project i tryed many cool tools for changelog generation. But (My needs is wery specific) none of them satisfied me, so I had to write my own action.

**Comment by mmaietta** [comment]
Would you be willing to share the action you route?

Right now I'm working on a PR labeler, Issue labeler, and Dependabot actions.
My next goal is to have automatic npm publishing from master on a daily or weekly basis, but that will require automatic changelog generation as well.

**Comment by cawa-93** [comment]
[My action](https://github.com/cawa-93/vite-electron-builder/tree/main/.github/actions/release-notes). But it very "project-specific"

**Pull request merged**
