### PR TITLE
Fix Problem building multiple mac targets:TypeError: pattern.startsWith is not a function

### PR DESCRIPTION
**Pull request by gaodeng**
more info https://github.com/electron-userland/electron-builder/issues/3012

### CODE REVIEW

**Comment by mmaietta** [comment]
This LGTM I think, but I'm wondering if we should cover this with some basic unit tests in fileTest.ts to validate the file pattern merges.  I was under the impression that `value` was an array.

Do you have a sample config for this?
I was trying to come up with some unit tests over the weekend, then my hackintosh crashed...so I'm working on fixing that

**Comment by gaodeng** [comment]
Hi @mmaietta , sorry for not replying in time, I've been too busy lately

Actually fileTest.ts is fine. The root of the problem is DebugLogger.ts, which changes the input parameters.

I'm afraid I can't simply give a configuration file to reproduce the problem. This is because the problem is caused by compiling mac and mas in parallel, so the problem is related to the performance of your machine, and the same configuration that reproduces the problem on my machine may not reproduce it on your machine. 

Fortunately, we already know what the problem is, and it's easy to fix

If you still want to reproduce the problem, you can try @mifi 's https://github.com/mifi/lossless-cut/pull/709, which is an open source project, and see if you can reproduce it on your machine

**Comment by mmaietta** [comment]
👍 Can you please rebase of latest master? Then we should be good to go

**Comment by gaodeng** [comment]
> 👍 Can you please rebase of latest master? Then we should be good to go

done

**Review by mmaietta — APPROVED** [review]

**Pull request merged**
