### PR TITLE
feat: Adding new downloadAlternateFFmpeg option to download non-proprietary ffmpeg library

### PR DESCRIPTION
**Pull request by mmaietta**
Implements #7210 

Credit to @burnhamup for PR example https://github.com/electron-userland/electron-builder/pull/7247 🙂

### CODE REVIEW

**Comment by AviVahl** [comment]
This change introduced a LOT of new dependencies and a vulnerability due to `request` being re-depended again.
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Server-Side Request Forgery in Request                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ request                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ electron-builder                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ electron-builder > app-builder-lib >                         │
│               │ electron-packager-plugin-non-proprietary-codecs-ffmpeg >     │
│               │ request                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1091459                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by mmaietta** [comment]
Hmmmmm, stay tuned for a 24.1.1 then. I'll try and take a different approach to maintain feature parity

**Comment by mmaietta** [comment]
@AviVahl released 24.1.1. Removed the dependency entirely and wrote it from scratch

**Comment by calisven** [comment]
@mmaietta CC @AviVahl Thanks so much for this change! I have a question about the non-proprietary FFmpeg library it pulls in. Can you provide a link to where it's hosted and which license it's under? Appreciate your time!

**Comment by mmaietta** [comment]
@calisven it comes from the official electron distro
https://github.com/electron-userland/electron-builder/blob/15ce5b4164378f7398ff84cabe8ee97eef5cfd1b/packages/app-builder-lib/src/electron/injectFFMPEG.ts#L12

**Pull request merged**
