### PR TITLE
fix: only unpack native `.node` modules, not all files in the parent folders

### PR DESCRIPTION
**Pull request by mmaietta**
Fixes: https://github.com/electron-userland/electron-builder/issues/8640

Reverts: https://github.com/electron-userland/electron-builder/pull/8392

### CODE REVIEW

**Comment by beyondkmp** [comment]
I have a question: Should we apply the same treatment to exe and dll files as well, only extracting these specific files without unpacking other files in their parent folders?

**Comment by mmaietta** [comment]
@NoahAndrews that should still work based on this line of the `unpackDetector`
https://github.com/electron-userland/electron-builder/blob/ab50ad146143c554fb7a4470815a95966b559349/packages/app-builder-lib/src/asar/unpackDetector.ts#L17-L19

That being said, what dependency is this? I can test locally and/or whip up a unit test for it

We need a way to resolve #8640, but the caveat of a revert is that `**/*.node` will need to be manually specified in `asarUnpack`, which I'm adverse to doing. I'm trying to find a middleground that auto-unpacks only `.node` addons, while still any file that is `dll`/`so`/`dylib`/`exe` are also auto-unpacked with all parent files included

**Comment by NoahAndrews** [comment]
> We need a way to resolve #8640, but the caveat of a revert is that `**/*.node` will need to be manually specified in `asarUnpack`, which I'm adverse to doing. I'm trying to find a middleground that auto-unpacks only `.node` addons, while still any file that is `dll`/`so`/`dylib`/`exe` are also auto-unpacked with all parent files included

That sounds good. Looking at the actual changes in this PR, it doesn't look to me like there will be any behavior changes yet, is that accurate? I know this is still a draft.

> That being said, what dependency is this? I can test locally and/or whip up a unit test for it

Thanks! The package is https://www.npmjs.com/package/@rev-robotics/can-bridge.

While I really like the idea of a unit test for it, we're hoping to [migrate it to use static linking](https://github.com/REVrobotics/node-can-bridge/issues/13) in the near-to-medium term, so maybe it's not worth it. It's also currently Windows-only, so it wouldn't be a particularly thorough test case for cross-platform native addons that link against libraries dynamically. Your call though.

**Comment by mmaietta** [comment]
>it doesn't look to me like there will be any behavior changes yet, since isLibOrExe() is only called in the one place.

It's used in two places. `unpackDetector` and `appFileCopier`, albeit the latter has no logic changes, it was always including `.node` in its logic

**Comment by mmaietta** [comment]
Closing this, I think it's more worthwhile to auto unpack `.node` files as opposed to required to be specified for `asarUnpack`. This does result in parent folders+files being unpacked as well, but it does not really change the functionality or size of the bundled app - it's the same files being included.

**Pull request closed without merging**
