### PR TITLE
feat: implement autoupdates for pacman

### PR DESCRIPTION
**Pull request by xyloflake**
Introducing autoupdate support for pacman!

I have updated docs & tests plus ran all tests.

I have also pushed an update to the pnpm lockfile which was auto-generated during `pnpm update`

### CODE REVIEW

**Comment by xyloflake** [comment]
@mmaietta @beyondkmp Is this normal?
image
I only added minor bumps for `app-builder-lib` and `electron-updater` as is evident by e0f41a859f1df20c1ca8028a108b0329650234ed

**Comment by xyloflake** [comment]
As has been discussed in #8381, here's my PR @mmaietta!

**Comment by mmaietta** [comment]
Nice work @xyloflake! I'm going to work on getting a new release set up on my electron-builder-test repo so that we can have the `test pacman download` test pass

**Comment by xyloflake** [comment]
> Nice work @xyloflake! I'm going to work on getting a new release set up on my electron-builder-test repo so that we can have the `test pacman download` test pass

Yay! Thank you!

**Comment by xyloflake** [comment]
@mmaietta should this PR result in major or minor version bump? I think minor as according to semver the minor in MAJOR.MINOR.PATCH must be incremented when a new feature is implemented?

**Comment by xyloflake** [comment]
@mmaietta Hi, I wanted to give you an update on the asynchronous install PR—it's about 70% complete, and I'm in the phase of making and testing changes. I've realized that this PR will require another modification once the asynchronous PR is ready because the `doInstall` functions need to be asynchronous. 

The challenge is that I'm working on both PRs simultaneously. To avoid conflicts, one of these PRs will need to be merged after the other. Should I commit the necessary changes for `doInstall` in this PR or the other one?

**Comment by mmaietta** [comment]
It should be a `minor` bump. I'll take a look into why the Changelog CI action is showing up as a `major` bump. Nothing immediately stands out to me though

Regarding the rollout of this autoupdate feature. I think you'll need to do 2 releases, one with the initial pacman release with electron-updater pacman support integrated, then another release to actually trigger the pacman autoupdate feature.

Re: the `doInstall` logic needing to be async. Sounds like we need the async PR merged first (which I need to take a deeper review of), then we can circle back to this PR so you can merge in the latest `master` from that point?

**Comment by xyloflake** [comment]
> It should be a `minor` bump. I'll take a look into why the Changelog CI action is showing up as a `major` bump. Nothing immediately stands out to me though

Got it! Thanks.

> Regarding the rollout of this autoupdate feature. I think you'll need to do 2 releases, one with the initial pacman release with electron-updater pacman support integrated, then another release to actually trigger the pacman autoupdate feature.

That is absolutely correct, you need to make a release for 1.0.4 with initial Pacman support and then 1.0.5 for testing the update.

> Re: the `doInstall` logic needing to be async. Sounds like we need the async PR merged first (which I need to take a deeper review of), then we can circle back to this PR so you can merge in the latest `master` from that point?

Seems like the most appropriate thing to do! I'm completely okay with that :)

**Comment by xyloflake** [comment]
@mmaietta can we merge this instead? And change it for pacman in the other PR.

**Comment by mmaietta** [comment]
@xyloflake how can I test this locally on a linux VM? Preferably via Parallels Desktop. I trust your testing, but I feel I should still give it a look once-over

**Comment by xyloflake** [comment]
> @xyloflake how can I test this locally on a linux VM? Preferably via Parallels Desktop. I trust your testing, but I feel I should still give it a look once-over

You need some arch linux or derivative linux distro to support pacman. Otherwise there's no other way. If you want, I can give you remote access to my arch machine but we'd need to be in a call then because testing it is complicated. However I 100% do guarantee that this is not flawed and has been appropriately tested.

**Comment by xyloflake** [comment]
Alright I'll write up the instructions for once you get an arch VM up and running. Please use pnpm as patches are easier to configure. And most importantly, find out a way to display your version in the electron app before doing all of this as to confirm that update was indeed successful.

1. Create a sample electron app with electron builder support
2. Patch/Use yalc to link this PR's electron-updater and app-builder-lib for usage in the electron app
3. For patching you may use `pnpm patch app-builder-lib` and similarly for electron-updater
4. Configure feedurl provider to be `generic` and url being `http://127.0.0.1:8080`.
5. `pnpm i -g http-server`
6. `http-server -p 8080` - of course you can change the port according to your preference but if you do, change it in 4th step as well
7. Build one version as `pnpm build --linux pacman` - I'm assuming you've set up the build script.
8. After completion, install first version with `pacman -U yourapp.pacman`
9. Then build another version after changing version in package.json
10. Open the first app after completion and relaunch if already running
11. You will receive a notification saying that update is ready and will be installed once you quit
12. Quit the application
13. Enter password (you need to have a desktop environment setup btw)
14. Relaunch the app and check version

**Comment by xyloflake** [comment]
> @xyloflake how can I test this locally on a linux VM? Preferably via Parallels Desktop. I trust your testing, but I feel I should still give it a look once-over

Sorry I do not know how Parallel Desktop works and I haven't personally used it. But you'd need to setup an arch vm somehow to test this. And let me warn you before you try: installing arch is one of the most complicated things to do. One wrong command like using archinstall instead of the documented commands might break your system and drive. It's overwhelmingly frustrating and time consuming. It took me about 1.5 hours to get arch up and running.

If you have the time, patience and can afford breaking your system, I'll be happy to help. Otherwise this can go through an alpha version and once it's considered stable, we can make it beta.

**Comment by xyloflake** [comment]
I can upload a video proof of updation taking place if you want as well. My colleague @gamersi has also tested it on 2 different devices.

**Comment by gamersi** [comment]
> > @xyloflake how can I test this locally on a linux VM? Preferably via Parallels Desktop. I trust your testing, but I feel I should still give it a look once-over
> 
> Sorry I do not know how Parallel Desktop works and I haven't personally used it. But you'd need to setup an arch vm somehow to test this. And let me warn you before you try: installing arch is one of the most complicated things to do. One wrong command like using archinstall instead of the documented commands might break your system and drive. It's overwhelmingly frustrating and time consuming. It took me about 1.5 hours to get arch up and running.
> 
> If you have the time, patience and can afford breaking your system, I'll be happy to help. Otherwise this can go through an alpha version and once it's considered stable, we can make it beta.

On a VM you can just use archinstall, works 9/10 times as there is just one disk. Where archinstall is really bad is with custom disk configurations which you don't have on a VM.

**Comment by Bug-Reaper** [comment]
Happy to test w/Arch on real hardware if needed (been daily-driving arch since 2012).

**Comment by xyloflake** [comment]
> Happy to test w/Arch on real hardware if needed (been daily-driving arch since 2012). 

@Bug-Reaper please foll9w the step then and report if it autoupdates :)

**Comment by Bug-Reaper** [comment]
Hey @xyloflake just wanted to let you know I tentatively plan to test this either tmmo or Thurs!

CC: @mmaietta - I can screen-record this and/or assist w/your VM setup and potentially some type of automated VM/Docker setup for tests as needed just lmk 👍

**Comment by xyloflake** [comment]
> Hey @xyloflake just wanted to let you know I tentatively plan to test this either tmmo or Thurs!

Super cool! Looking forward to it :)

**Comment by xyloflake** [comment]
@mmaietta have you tested it yet?

**Comment by mmaietta** [comment]
@xyloflake Haven't had time to set up my dev environment. Will be back from vacation on 8/3

**Comment by mmaietta** [comment]
Update:
- I'm currently unable to set up ArchLinux in a Parallels VM. I've attempted to follow their tutorial, but it's not picking up any bootable image for some reason when setting up a new VM. Perhaps due to me using an M2 mac?

Developer's note: Instead of using yalc, I just use resync to force copy all additional assets over to my test project (assuming the projects in the same root dir (~/Development in my case). I've saved it as an alias in my zsh profile for easy access
```
alias resync="rsync -upaRv --include='*.js' --include='*.d.ts' --include='*.nsi' --include='*.json' --include='*/' --include='*.py*' --include='*.tiff' --exclude='*'  ~/Development/electron-builder/packages/./* node_modules/"
```

**Comment by xyloflake** [comment]
@mmaietta that's quite sad to hear. I hope you through it soon and best wishes from my end. All I can say that all life on earth has to come to an unfortunate end and it's pretty sad. I hope you find the strength and courage to get over it and remember that person with all the good memories. I am so so sorry.

**Comment by xyloflake** [comment]
> Update:
> - I'm currently unable to set up ArchLinux in a Parallels VM. I've attempted to follow their tutorial, but it's not picking up any bootable image for some reason when setting up a new VM. Perhaps due to me using an M2 mac?

Sorry, I don't really know about parallels vm so I'll request @gamersi to help you if possible.

> Developer's note: Instead of using yalc, I just use resync to force copy all additional assets over to my test project (assuming the projects in the same root dir (~/Development in my case). I've saved it as an alias in my zsh profile for easy access
> ```
> alias resync="rsync -upaRv --include='*.js' --include='*.d.ts' --include='*.nsi' --include='*.json' --include='*/' --include='*.py*' --include='*.tiff' --exclude='*'  ~/Development/electron-builder/packages/./* node_modules/"
> ```

I've never even heard of resync. What we do at muffon for consistency and development testing is that we do a simple pnpm patch and then copy the electron builder source build with the out folder contents and then finally we do pnpm patch-commit. Of course it is inefficient but it's the most stable among all because yalc sometimes skips changes and it's pretty hard to say if the version was changed or not without opening node modules.

**Comment by mmaietta** [comment]
> copy the electron builder source build with the out folder contents

That's what `rsync` is performing to copy directly from `electron-builder/packages` into the local project's node_modules dir . I just shortcut the command to an alias in my zsh profile so that I can simply call `resync` in Terminal from my app project's directory. I found it more powerful than `yalc` for handling additional file types via `--include`

**Comment by gamersi** [comment]
> > copy the electron builder source build with the out folder contents
> 
> That's what `rsync` is performing to copy directly from `electron-builder/packages` into the local project's node_modules dir . I just shortcut the command to an alias in my zsh profile so that I can simply call `resync` in Terminal from my app project's directory. I found it more powerful than `yalc` for handling additional file types via `--include`. Helps streamline my work on my mac 🙂

Why rsync and not cp? Isn’t rsync made for copying over network?

concering the VM - you are not gonna have much luck with virtualization - there is arch Linux arm but it only has 1 maintainer who is so overworked that he sometimes doesn’t have time to update to the latest kernel. You could use that but support is bad and versions are sometimes weeks to months behind. So I would recommend to emulate x86-64

**Comment by xyloflake** [comment]
> > > copy the electron builder source build with the out folder contents
> > 
> > That's what `rsync` is performing to copy directly from `electron-builder/packages` into the local project's node_modules dir . I just shortcut the command to an alias in my zsh profile so that I can simply call `resync` in Terminal from my app project's directory. I found it more powerful than `yalc` for handling additional file types via `--include`. Helps streamline my work on my mac 🙂
> 
> Why rsync and not cp? Isn’t rsync made for copying over network?
> 
> concering the VM - you are not gonna have much luck with virtualization - there is arch Linux arm but it only has 1 maintainer who is so overworked that he sometimes doesn’t have time to update to the latest kernel. You could use that but support is bad and versions are sometimes weeks to months behind. So I would recommend to emulate x86-64

Absolutely correct. Trying on a M series macbook will create problems nevertheless because of the ARM architecture.

**Comment by mmaietta** [comment]
So I can't figure out why `app-builder-lib: minor` version bump is causing changesets-cli to flag it as a `major` semver bump. I've worked around it by converting the field to a `patch` for app-builder-lib

**Comment by mmaietta** [comment]
@xyloflake @Bug-Reaper In order to move forward, I'd like evidence that the update process completes successfully (since I can't set up an Arch Linux VM on arm64 macs from what I am understanding)

Please post back logs from electron-updater as well so that we can debug anything further (if necessary). Logging can be added via:
```
    const log = require("electron-log")
    log.transports.file.level = "debug"
    autoUpdater.logger = log
```

**Comment by gamersi** [comment]
> @xyloflake @Bug-Reaper @gamersi  In order to move forward, I'd like evidence that the update process completes successfully (since I can't set up an Arch Linux VM on arm64 macs from what I am understanding)
> 
> 
> 
> Please post back logs from electron-updater as well so that we can debug anything further (if necessary). Logging can be added via:
> 
> ```
> 
>     const log = require("electron-log")
> 
>     log.transports.file.level = "debug"
> 
>     autoUpdater.logger = log
> 
> ```

You can test it:
Parallels cannot emulate so ots not possible.
There is another well known program for that(which i have used personally on my iphone for the same task): UTM
It can emulate architectures and i think it even has a preconfigured arch VM somewhere on their site: https://mac.getutm.app/
Another benefit: it's FOSS(not like parallels)

https://github.com/utmapp/UTM

It is also based on QEMU which is very well developed and has been around for quite some time

**Comment by xyloflake** [comment]
> @xyloflake @Bug-Reaper @gamersi  In order to move forward, I'd like evidence that the update process completes successfully (since I can't set up an Arch Linux VM on arm64 macs from what I am understanding)
> 
> Please post back logs from electron-updater as well so that we can debug anything further (if necessary). Logging can be added via:
> ```
>     const log = require("electron-log")
>     log.transports.file.level = "debug"
>     autoUpdater.logger = log
> ```

We can do that. Cool idea. Saves a lot of manual labour actually for ya. 

@gamersi since I'm busy and will reach home around 12:30pm ET, can you make a build of muffon and send the logs here? 

I'll be late as I have school today 🙂

**Comment by mmaietta** [comment]
My localhost `minio` update server is completely broken such that publishing hangs indefinitely and I haven't been able to resolve that issue yet.

Would really appreciate it if you could test locally and provide logs to exemplify that the entire process works e2e
>I'd like evidence that the update process completes successfully.
Please post back logs from electron-updater as well so that we can debug anything further (if necessary).

**Comment by xyloflake** [comment]
> My localhost `minio` update server is completely broken such that publishing hangs indefinitely and I haven't been able to resolve that issue yet.
> 
> Would really appreciate it if you could test locally and provide logs to exemplify that the entire process works e2e
> 
> > I'd like evidence that the update process completes successfully.
> > Please post back logs from electron-updater as well so that we can debug anything further (if necessary).

@gamersi please do as instructed.

**Comment by gamersi** [comment]
@mmaietta

I have done the full update process locally.

Here is a screenrecording and the log file:

[main.log](https://github.com/user-attachments/files/17215137/main.log)
[Screencast From 2024-10-01 21-08-48.webm](https://github.com/user-attachments/assets/237fb748-ae2a-4836-9e3a-67b6b2621ce9)

**Comment by xyloflake** [comment]
> Looking good! 

Thank you!

> Two remaining questions. Is the "Application not responding" popup expected though (i.e. do you manually have to close the app or is it automatic as expected)? 

My extensive tests done with my team showed that manually closing the app in the best case would fail the update or in the worst case corrupt the existing application. The app should let be on its own and let it close by itself otherwise unknown consequences happen and there's a perfect 100% chance that the update won't complete.

> And does the app properly relaunch after update if `isForceRunAfter: true`?

Yes, obviously it does. If you want, we can run that as well but I don't think it's necessary to retest (again). Is there anything that tells you something might create a problem for `isForceRunAfter`?

**Comment by mmaietta** [comment]
> My extensive tests done with my team showed that manually closing the app in the best case would fail the update or in the worst case corrupt the existing application. The app should let be on its own and let it close by itself otherwise unknown consequences happen and there's a perfect 100% chance that the update won't complete.

I suppose that'd be the same case then as with rpm and deb updaters if the update process is interrupted, and potentially the mac updater as well (not sure how electron's autoupdater internally handles updating app resources). I don't recall those apps throwing a popup of the app not responding though.

>Is there anything that tells you something might create a problem for isForceRunAfter?

Just wanted to make sure the `relaunch` sequence works as expected as I'm completely unfamiliar with pacman.

I think the final steps here are just to rebase/merge in latest `master` and then we're probably good to go.
@beyondkmp let me know if you have any feedback/comments on this PR 👀

**Comment by xyloflake** [comment]
> > My extensive tests done with my team showed that manually closing the app in the best case would fail the update or in the worst case corrupt the existing application. The app should let be on its own and let it close by itself otherwise unknown consequences happen and there's a perfect 100% chance that the update won't complete.
> 
> I suppose that'd be the same case then as with rpm and deb updaters if the update process is interrupted, and potentially the mac updater as well (not sure how electron's autoupdater internally handles updating app resources). I don't recall those apps throwing a popup of the app not responding though.


Oh yea we tested for othe platforms as well. The corruption happens with deb and rpm packages as far as we know. Pacman's installation system doesn't corrupt the binaries but for sure does not install if force quitted midway. Also we've got all platforms to throw the not responding popup.

> >Is there anything that tells you something might create a problem for isForceRunAfter?
> 
> Just wanted to make sure the `relaunch` sequence works as expected as I'm completely unfamiliar with pacman.
> 
> I think the final steps here are just to rebase/merge in latest `master` and then we're probably good to go.

I think github has an option to "rebase and merge to master" which I quite frequently use. Can you enable that and perhaps rebase while merging to master?

**Comment by xyloflake** [comment]
@mmaietta I think I've rebased, can you check?

**Comment by mmaietta** [comment]
Looks like no, let me see if I can tackle pulling in latest master

**Comment by xyloflake** [comment]
> We're investigating having it as an async process in a detached shell, however, it breaks NSIS updaters currently. It's a future project but I have bigger fish to fry atm 😅 

I think you're talking about me lol. I'm the one who opened that draft PR and reported NSIS isn't working.

**Comment by xyloflake** [comment]
@mmaietta are you talking about #8405? In that case, that'd be me 😄

**Comment by mmaietta** [comment]
Haha yep, that's you. My bad 😅 

@beyondkmp any feedback on this PR? Otherwise, I think it may be good to merge. (Still trying to figure out how to get a `minor` semver bump without it being a `major` semver update per the changesets CI - right now I've set it to patch for app-builder-lib, but ideally this should be a `minor` bump)

**Comment by xyloflake** [comment]
> Haha yep, that's you. My bad 😅 

No problem 😄

I'll be working on it after my exams, which are keeping me busy atm but thank you for the acknowledgement.

**Comment by xyloflake** [comment]
@mmaietta can we merge then?

**Comment by xyloflake** [comment]
@mmaietta ?

**Comment by beyondkmp** [comment]
> Haha yep, that's you. My bad 😅
> 
> @beyondkmp any feedback on this PR? Otherwise, I think it may be good to merge. (Still trying to figure out how to get a `minor` semver bump without it being a `major` semver update per the changesets CI - right now I've set it to patch for app-builder-lib, but ideally this should be a `minor` bump)

LGTM.

**Review by beyondkmp — DISMISSED** [review]

**Comment by beyondkmp** [comment]
@mmaietta If you don't have any other questions, I will merge this in.

**Comment by beyondkmp** [comment]
@xyloflake Can we refer to macOS's incremental upgrade and see if it's possible to implement incremental upgrades on Linux as well?

**Comment by xyloflake** [comment]
> @xyloflake Can we refer to macOS's incremental upgrade and see if it's possible to implement incremental upgrades on Linux as well?

Hello again! I'll have a look at the incremental update code just to make sure I know what we're working with, to make sure that I can tell how complex it would be. @beyondkmp

**Comment by xyloflake** [comment]
@beyondkmp at a first glance, nothing in the differential update code seems to contain macOS specific code. It *should* be migratable to linux kind of easily.

That being said, it might not be as easy if we try to implement it. I'll take a look whenever I can and will open a PR if I succeed, sounds good?

**Comment by beyondkmp** [comment]
> @beyondkmp at a first glance, nothing in the differential update code seems to contain macOS specific code. It _should_ be migratable to linux _kind of_ easily.
> 
> That being said, it might not be as easy if we try to implement it. I'll take a look whenever I can and will open a PR if I succeed, sounds good?

Great.

**Comment by mmaietta** [comment]
@xyloflake just a heads up since I think you were using a patch file while electron-updater was in alpha. It's been fully released to `next` tag, most recent release is 6.4.1.

**Comment by xyloflake** [comment]
> @xyloflake just a heads up since I think you were using a patch file while electron-updater was in alpha. It's been fully released to `next` tag, most recent release is 6.4.1.

Thank you!

**Pull request merged**
