### PR TITLE
Update installer.nsi

### PR DESCRIPTION
**Pull request by sante85**
added preInstall macro

### CODE REVIEW

**Comment by develar** [comment]
Could you please explain for what? Maybe `customHeader` is enough?

**Comment by develar** [comment]
Or `preInit`?

**Comment by sante85** [comment]
i want prevent installation, if a condition is satisfied, and do custom action.

i have tested **preInit**, that is called at build installer, and **customInstall** is called after setup installer.
**customHeader** is after executing setup installer, right?!

**Comment by develar** [comment]
As you can see, we call `check64BitAndSetRegView` and `ALLOW_ONLY_ONE_INSTALLER_INSTANCE ` in the `.onInit`. And it is the right and correct place to add some custom check before install. So, I don't understand why `preInit` macro is not suitable for you to add custom check.

**Comment by sante85** [comment]
Yes, you have right mode, i set Preinit again and do correctely.

Best regards

**Pull request closed without merging**
