### PR TITLE
fix: Do not run node modules file matcher when node_modules are handl…

### PR DESCRIPTION
**Pull request by wojtkowiak**
…ed externally

Resolves https://github.com/electron-userland/electron-builder/issues/2951#issuecomment-392489184

### CODE REVIEW

**Comment by fubhy** [comment]
Checking if there is a node_modules directory or not within the app directory is not good enough. In case of more complex setups e.g. with yarn workspaces, the node modules directory might be entirely hoisted to the workspace root, resulting in no node_modules within the app directory.

**Comment by wojtkowiak** [comment]
Ok, I get it, good point. I do not use `yarn workspaces` so I was not aware of this possibility. I rewrote it to use the same information I used before and that is resolving `beforeBuild` hook to `false`.
I am already using that to prevent `electron-builder` from installing dependencies because they are handled externally so I already have this information passed to electron-builder so it probably better to just reuse that.

**Comment by wojtkowiak** [comment]
@devlar sorry for pinging you, but I need to get it working as this is a blocker for next `meteor-desktop` as the integration is not working at all without this.

**Comment by develar** [comment]
Sorry for delay, will be addressed tomorrow morning CET.

**Comment by wojtkowiak** [comment]
Thanks a lot 👍

**Pull request merged**
