### PR TITLE
add proxy authentication support to electron-updater

### LINKED ISSUE #1528: [electron-updater] proxy authentication
* **Version**: latest

Hi,
currently it seems like the `login` events of the net.requests created in [`electronHttpExecutor`](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/electronHttpExecutor.ts) cannot be intercepted by the user which is obviously problematic if the app is used behind a proxy that requires authentication.
Would a PR to resolve this be accepted? If yes, do you have any design guidelines/ preferences?

### PR DESCRIPTION
**Pull request by BurningEnlightenment**
With this approach we simply relay the login event from the electron requests to the `autoUpdater` instance through a callback provided by an (optional) constructor parameter of `ElectronHttpExecutor`.
The test suite runs; but I haven't had time to test the change specifically, but uploaded it in order to allow for early feedback on the general approach.

resolves #1528

### CODE REVIEW

**Comment by BurningEnlightenment** [comment]
@develar Why does `doApiRequest()` use the default session instead of the electron updater session?

**Comment by develar** [comment]
I think it is bug.

**Comment by BurningEnlightenment** [comment]
> I think it is bug.

Shall I add a commit fixing it to this PR?

**Comment by develar** [comment]
Yes, please.

**Comment by develar** [comment]
Danke!

**Comment by develar** [comment]
electron-updater 1.15.0

**Pull request closed without merging**
