### PR TITLE
Added Slovak(sk) translations

### PR DESCRIPTION
**Pull request by daikiuk**

### CODE REVIEW

**Comment by develar** [comment]
Thanks. Ignore CI errors — only I can fix it. `sk` NSIS bundle is required to be bundled as well.

**Comment by develar** [comment]
Could you please also translate boringMessages.yml?

**Comment by daikiuk** [comment]
Will do.



*Daniel Dzurov**Director*


T: +44 (0)20 7193 8559
M: +44 (0)79 3114 1425
E: daniel.dzurov@xtmotion.co.uk
W: www.xtmotion.co.uk

[image: XTmotion: Complete Website Solutions] <http://www.xtmotion.co.uk/>
[image: Derryn Coetzee LinkedIn Profile]
<http://www.linkedin.com/in/danieldzurov> [image: XTmotion on Facebook:
Complete Website Solutions]
<http://www.facebook.com/pages/Orpington-United-Kingdom/Web-Design-Website-Development-XTmotion/110894225608729>
[image:
XTmotion on Twitter: Complete Website Solutions]
<http://twitter.com/XTmotion>
__________________________________________________________________________

*XTmotion Limited* is a company registered in England. Company Registration
No. *4973422*.
Registered Office: 1 Bromley Lane, Chislehurst, BR7 6LH

**Comment by develar** [comment]
Merged, sk nsis added, release will be today. Boring installer message is welcome.

**Comment by daikiuk** [comment]
Great, just created PR

**Pull request closed without merging**
