### PR TITLE
fix(differential updates): emit progress events

### PR DESCRIPTION
**Pull request by the3moon**
In response to #2521 I added some logic to emit differential update progress on NSIS and AppImage.

### CODE REVIEW

**Comment by sandeep1995** [comment]
@the3moon Why was this closed?

**Comment by harshitsilly** [comment]
@sandeep1995 @the3moon - Hi, try this module [electron-differential-updater](https://imjselectron.github.io/electron-differential-updater/#/).. it is built on top of electron-builder and help u with the fix.
It also has differential update for mac also.

**Comment by JonathanLydall** [comment]
@the3moon, also curious on your reasoning for closing this PR.

**Comment by the3moon** [comment]
I closed this because I found out that it does not work properly. And I was lazy to fix this. Let me know if you want me to reopen :)

**Comment by JonathanLydall** [comment]
Thank you @the3moon, appreciate the explanation.

**Pull request closed without merging**
