### PR TITLE
fix: correct native dependency tree mismatch in app-builder rebuild

### PR DESCRIPTION
**Pull request by leey0818**
This PR fixes the mismatch in the dependency tree structure provided by the rebuild-node-modules command in the app-builder binary.

### CODE REVIEW

**Comment by mmaietta** [comment]
@beyondkmp can you take a look at this when you have a chance? This PR is proposing conditionally applying the `--flatten` flag.

**Comment by mmaietta** [comment]
@leey0818 do you have a github issue that this is fixing? Or can you provide a minimal repro repo as to what the issue is originally? I'd like to create a unit test for this if possible

**Comment by beyondkmp** [comment]
@mmaietta This PR should be able to fix the issue(https://github.com/electron-userland/electron-builder/issues/8426#issuecomment-2336636232)

**Comment by mmaietta** [comment]
> I have a question: will the legacy configuration for nativeRebuilder be deprecated in the future, or will it be retained permanently?

Probably retained for quite some time, but eventually deprecated and finally removed. Just want to make it easy to debug any issues that arise between app-builder-bin migration to electron-rebuild. electron-builder v25 still doesn't have broad adoption as `latest` tag

**Comment by leey0818** [comment]
@mmaietta I have created a GitHub issue (#8459).

Using the legacy option to utilize pre-built native dependencies in a cross-platform build. It seems that @electron/rebuild does not yet support cross-platform builds.

**Comment by beyondkmp** [comment]
LGTM

**Comment by leey0818** [comment]
Fixed #8459

**Pull request merged**
