### PR TITLE
feat: Added an option to force NSIS to use the 64-bit program files install directory.

### PR DESCRIPTION
**Pull request by aulvi**
I didn't see a way to easily influence which install directory was used so I cobbled this together.

### CODE REVIEW

**Comment by develar** [comment]
I don't like implemented solution because new option is added. I think we should install 64-bit version to `$PROGRAMFILES64` by default.

**Comment by aulvi** [comment]
@develar I hear you and will submit another PR with that (very minor) change.

However, I still believe the best approach would be allowing the developer to choose the installation path. Would you be willing to accept a PR where we use the --x86/--ia32 flags to influence where the installer sticks things? I imagine I'll need a 32-bit installer at some point.

**Comment by develar** [comment]
@aulvi Please see https://github.com/electron-userland/electron-builder/blob/master/templates/nsis/installSection.nsh#L107

if `${RunningX64}` and `APP_64` is defined, then we should install to `$PROGRAMFILES64`

**Comment by aulvi** [comment]
@develar Awesome, I'll make the necessary changes and re-submit later today (meetings up next).

Regarding contributing, I seem to have issues making commits without --no-verify, tests failing, etc. Is this just the current state of things or is my local dev environment in need of more tweaking? Thanks!

**Comment by develar** [comment]
> Regarding contributing, I seem to have issues making commits without --no-verify, tests failing, etc. Is this just the current state of things or is my local dev environment in need of more tweaking? Thanks!

Works for me on macOs. Please specify error detailes / failed tests / your platform.

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#debug-tests You don't need to wait the whole run to test only one test case.

**Comment by aulvi** [comment]
@develar Hey, I really appreciate your work, this is a super useful project. Thanks so much.

My build env: OSX Sierra, Node v7.0.0, NPM v3.10.8, Yarn v0.16.1.

Here is some of the output from `npm test`, please let me know if you'd like the full output:

```
Packaging for platform darwin x64 using electron 1.4.0 to dist/mac

  ✔ nsisUpdaterTest › check updates - no versions at all (5.5s)
  ✔ BuildTest › extra metadata - two (17.9s)
  ✔ nsisUpdaterTest › cannot find suitable file for version (5.5s)
  ✖ test/out/globTest.js exited due to SIGSEGV
  ✔ nsisUpdaterTest › file url (6.2s)
  ✔ nsisUpdaterTest › file url generic 
```
and
```
Building NSIS installer

  ✔ nsisTest › installerHeaderIcon (1m 2.6s)
  ✔ nsisTest › custom include (1m 2.7s)
  ✔ nsisTest › perMachine, no run after finish (1m 6.6s)
  ✔ linuxPackagerTest › no-author-email (17.9s)
  ✔ linuxPackagerTest › AppImage (20.6s)
  ✔ linuxPackagerTest › icons from ICNS (22s)
  ✔ linuxPackagerTest › AppImage - default icon (23.5s)
  ✔ nsisTest › boring, only perMachine (1m 19.1s)
  ✔ nsisTest › boring (1m 19.9s)
  ✔ winPackagerTest › win (1m 45.2s)
  ✔ winPackagerTest › beta version (1m 45.1s)
  ✔ winPackagerTest › beta version (1m 45.8s)
  ✔ nsisTest › one-click (1m 25.9s)
  ✔ linuxPackagerTest › arm deb (43.8s)
  ✔ nsisTest › boring, MUI_HEADER as option (1m 38.5s)
  ✔ linuxPackagerTest › deb (52.3s)
  ✔ macPackagerTest › one-package (1m 43.1s)
  ✔ linuxPackagerTest › custom depends (52s)
  ✔ macPackagerTest › no build directory (1m 53.6s)
  ✔ macPackagerTest › two-package (1m 58.3s)
  ✔ macPackagerTest › no background (1m 55.9s)
  ✔ macPackagerTest › unset dmg icon (1m 56.4s)
  ✔ linuxPackagerTest › rpm and tar.gz (1m 12.3s)
  ✔ linuxPackagerTest › tar (2m 3.6s)
  ✔ linuxPackagerTest › targets (2m 58.2s)

  73 tests passed [09:48:02]
  2 tests skipped
  1 uncaught exception

Error: /Users/adam/Projects/ZHealth/electron-builder/node_modules/.bin/ava exited with code 1
    at ChildProcess.childProcess.once.code (/Users/adam/Projects/ZHealth/electron-builder/src/util/util.ts:165:14)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (/Users/adam/Projects/ZHealth/electron-builder/src/util/util.ts:128:3)
    at runTests (/Users/adam/Projects/ZHealth/electron-builder/test/src/helpers/runTests.ts:133:3)
    at /Users/adam/Projects/ZHealth/electron-builder/test/src/helpers/runTests.ts:30:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at main (/Users/adam/Projects/ZHealth/electron-builder/test/out/helpers/runTests.js:30:21)
    at Object.<anonymous> (/Users/adam/Projects/ZHealth/electron-builder/test/src/helpers/runTests.ts:37:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/adam/.nvm/versions/node/v7.0.0/bin/node" "/Users/adam/.nvm/versions/node/v7.0.0/bin/npm" "run" "test"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! electron-builder@0.0.0-semantic-release test: `node ./test/out/helpers/runTests.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-builder@0.0.0-semantic-release test script 'node ./test/out/helpers/runTests.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-builder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./test/out/helpers/runTests.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-builder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-builder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adam/Projects/ZHealth/electron-builder/npm-debug.log
```

**Comment by develar** [comment]
> test/out/globTest.js exited due to SIGSEGV

Known (since recently) blink test. I will fix it soon.

**Comment by aulvi** [comment]
Okay cool. I had other issues too but they were resolved by brew installing `lzip` and `rpm`, so I'm in fine shape now.

**Comment by develar** [comment]
Just to be sure that you don't waste your time: to run particalar test case:

`TEST_APP_TMP_DIR=/tmp/electron-builder-test NODE_PATH=. ./node_modules/.bin/ava --match="boring" test/out/nsisTest.js`

where `TEST_APP_TMP_DIR` is specified to easily inspect and use test build.

`boring` is the test name and `test/out/nsisTest.js` path to test file.

**Comment by aulvi** [comment]
Great feedback, thanks. I'm still spinning up on your project and appreciate the support.

**Pull request closed without merging**
