### PR TITLE
fix(nsis): fix per-machine installs

### LINKED ISSUE #6425: electron-updater@next breaks NSIS "per machine" quitAndInstall() when not using silent mode
* **Electron-Builder Version**: 22.14.7

* **Node Version**: 16.13.0

* **Electron Version**: 15.3.1
* **Electron Type (current, beta, nightly)**: current

* **Electron-Updater Version**: 4.6.2

* **Target**:  Windows NSIS

When we move from electron-updater `latest` to `next` to pick up the `autoInstallOnAppQuit` fix for MacOS, it breaks the previously working auto-updater for NSIS when installing for "All Users" (works fine if installed using the "Only for Me" option).

What I am seeing is a little strange in that the very first time I run the installer (unsigned and built locally), the quitAndInstall() call works as expected.  However, if I uninstall the application and then install again, the quitAndInstall() call gets to the point of causing Windows to pop up the UAC dialog asking for permission but then nothing else happens (that is, the Installer dialog does not appear).  If I run the app again and call quitOnInstall(), it works as expected.  After that first time, this behavior is repeatable every single time.

In looking at the log file (produced by our logger that we pass onto the autoUpdater), the log entries are always the same:

```
info: Checking for update
info: Found version 1.0.0 (url: WebLogic-Kubernetes-Toolkit-UI-Setup-1.0.0.exe)
info: Downloading update from WebLogic-Kubernetes-Toolkit-UI-Setup-1.0.0.exe
debug: updater cache dir: C:\Users\rhpat\AppData\Local\wktui-updater
info: Update has already been downloaded to C:\Users\rhpat\AppData\Local\wktui-updater\pending\WebLogic-Kubernetes-Toolkit-UI-Setup-1.0.0.exe).
info: Download complete, install type: now
info: Install on explicit quitAndInstall
info: Install: isSilent: false, isForceRunAfter: true, installPathRequiresElevation: true
info: isAdminRightsRequired is set to true, run installer using elevate.exe
```

If I don't change anything other than to drop back to electron-updater@latest, everything works as expected the first time, every time.  If it will help, I can pass you an installer built with electron-updater@next that reproduces the bad behavior.  Please let me know what I can do to help move this forward.

### PR DESCRIPTION
**Pull request by robertpatrick**
Add @krisdages changes from PR #6438 to elevate silent per-machine installs.
Remove PR #6073 that incorrectly elevates all per-machine installs, breaking interactive per-machine installs.

Closes #6425, #5468

### CODE REVIEW

**Comment by robertpatrick** [comment]
@mmaietta Not sure what to do about these tests since I am unable to get the tests to execute even without these changes.

**Comment by robertpatrick** [comment]
@mmaietta I am far from an NSIS scripting expert but the errors seem to indicate that the variable `hasPerMachineInstallation` is not always defined when the install script tries to access it.  

In looking at the place referenced by the comment in PR #6438 that I copied over, the variable is defined like this:

```
!ifndef INSTALL_MODE_PER_ALL_USERS
  !ifndef ONE_CLICK
    Var hasPerUserInstallation
    Var hasPerMachineInstallation
  !endif
  Var PerUserInstallationFolder
  ...
```

but in the changes in the `installer.nsi` file, it is protected only by:

```
  !ifndef BUILD_UNINSTALLER
    ${if} $hasPerMachineInstallation == "1" # set in onInit by initMultiUser
    ...
```

I don't feel like I understand the exact implications of these various ifndef variables but I am experimenting with changes that will both allow those 15 failing tests (which thankfully, I am able to run one-by-one from IntelliJ even though the full `pnpm test` is still failing with dozens of errors even when run directly on master) and my installer to work properly.  I will update the PR if/when I figure out the magic combination that fixes the failing unit tests and allows my installer to work properly...

**Comment by robertpatrick** [comment]
@mmaietta OK, this looks like a winner.  All unit tests seem to be passing and the 4 installer scenarios are working with my application:

1. per-machine, quitAndInstall()
2. per-machine, autoInstallOnAppQuit
3. per-user, quitAndInstall()
4. per-user, autoInstallOnAppQuit

**Comment by mmaietta** [comment]
This is awesome.

Thank you @robertpatrick  and @krisdages for your great work here!

**Review by mmaietta — APPROVED** [review]

**Pull request merged**
