### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by johnmuhl**
Refs: https://github.com/electron-userland/about/pull/4

### CODE REVIEW

**Comment by develar** [comment]
Since it is not an actual problem, I prefer to not complicate readme and move it to CONTRIBUTING.md

**Comment by johnmuhl** [comment]
Sure thing. Do you have a preferred placement? How about placing it after:

> You decided to contribute to this project? Great, thanks a lot for pushing it.

Would you prefer a new PR or a force push to this one?

**Comment by develar** [comment]
> How about placing it after:

👍 

> Would you prefer a new PR or a force push to this one?

force push, in any case I will squash commits.

**Comment by johnmuhl** [comment]
Sorry about the new line at the end of the file but I tried 4 editors on my linux system and they all insist upon it. :confused:

**Comment by develar** [comment]
Thanks.

**Pull request merged**
