### PR TITLE
Added "path.resolve()" to "const shimPath"

### PR DESCRIPTION
**Pull request by Megajin**
This will resolve the "__shim.js" not found issue. #2319

### CODE REVIEW

**Comment by develar** [comment]
Here should be projectDir, right?

**Comment by Megajin** [comment]
> Here should be projectDir, right?

Yes, the problem was that windows did not resolve the shim.js path. 
For example before the changes:
`C:\ProjectDir\App/__shim.js`

after the change:
`C:\ProjectDir\App\__shim.js`

**Comment by develar** [comment]
Thanks for spotting it! 

So, better fix will be using `path.sep` instead of using `path.resolve` just to normalise file path, right?

**Comment by Megajin** [comment]
> Thanks for spotting it!
> So, better fix will be using path.sep instead of using path.resolve just to normalise file path, right?

I'm not sure. Both can work obviously. However `path.sep` will only normalize the seperators, whereas `path.resolve`:

> If after processing all given path segments an absolute path has not yet been generated, the current working directory is used. The resulting path is normalized and trailing slashes are removed unless the path is resolved to the root directory. Zero-length path segments are ignored. If no path segments are passed, path.resolve() will return the absolute path of the current working directory.

Based on the docs I'd say it is safer to use `path.resolve`.

**Comment by develar** [comment]
`mainFileSet.src` should be absolute path. In any case it is not correct to assume that current working dir will be equal to project dir, so, `projectDir` should be used.

**Comment by Megajin** [comment]
> mainFileSet.src should be absolute path. In any case it is not correct to assume that current working dir will be equal to project dir, so, projectDir should be used.

True... so I will change this:

`  const shimPath = path.resolve(`${mainFileSet.src}/${ELECTRON_COMPILE_SHIM_FILENAME}`)`

to that:

  const shimPath = `${mainFileSet.src}${path.sep}${ELECTRON_COMPILE_SHIM_FILENAME}`

right?

**Comment by develar** [comment]
Yes. It is not about "do not call path.resovle if not need", but to make code clear and avoid question "why path.resolve is used if mainFileSet.src guarantied to be absolute?"

**Comment by Megajin** [comment]
> Yes. It is not about "do not call path.resovle if not need", but to make code clear and avoid question "why path.resolve is used if mainFileSet.src guarantied to be absolute?"

Done =).

**Comment by develar** [comment]
Thanks!

**Pull request merged**
