### PR TITLE
fix(msi): fix broken shortcut icon when using msi target

### PR DESCRIPTION
**Pull request by erikrz**
fix (msi): broken shortcut icon (#5965)

Add MSI option "iconId", replaces old static "icon.ico" icon identifier.

### CODE REVIEW

**Comment by mmaietta** [comment]
Is this backward compatible with previous builds? Just want to make sure the icon doesn't break when an update is installed.

**Comment by erikrz** [comment]
Yes, it does not impact app icons in taskbar, installer and uninstaller. 
It only fixes start menu and desktop shortcut icons, which have been broken for a while because we did not comply with how the data is required by Wix.

**Comment by mmaietta** [comment]
Can you try rebasing this off latest `master`? I'm not sure why the doc generator is failing.

**Comment by hasanatmango** [comment]
@erikrz Where we need to add `iconId` in package.json file ?

**Pull request merged**
