### PR TITLE
Added basic badges.

### PR DESCRIPTION
**Pull request by havenchyk**
Missed one for appveyor, because it fails on master.

### CODE REVIEW

**Comment by develar** [comment]
Why test and deps are useful? Tests in master should be green. Deps maintained by bot greenkeeper.

Npm version is useful, is it possible to fix command — `--save-dev` should be used.

**Comment by havenchyk** [comment]
Since we use greenkeeper, deps will not be useful. As for npm version, it can be either small badge with version only or bigger badge from nodei.co. I think it will be enough to have version only.

As for tests, yes, they always should green on master, but the badge will indicate about meging issues, I guess.

**Comment by havenchyk** [comment]
I'll provide an updated commit today, hopefully.

**Comment by develar** [comment]
> the badge will indicate about merging issues, I guess.

About pull request? Why it is interesting for users?

**Comment by havenchyk** [comment]
As a user i like to see that master is green and if it's not, the package is nit really well maintained. Anyway, if you don't see the reason to have it, I'll remove this badge.

**Comment by develar** [comment]
CI runs tests on push. If no one push — no run. So it will be green after last push and, so, it is not indicator if activity.

I think, "small badge with version only" will be useful, other badges is a visual noise.

**Comment by havenchyk** [comment]
Continued in #295

**Pull request closed without merging**
